<div class="panel panel-primary">
	<div class="panel-heading">
	<b>Servicio</b>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<div class="bs-docs-example no-code">
				  Producto: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>
				<div class="bs-docs-example no-code">
				  Solicit&oacute;: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>					        
			</div>
			<div class="col-md-4">
				<div class="bs-docs-example no-code">
				  Ejecutivo: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>			
				<div class="bs-docs-example no-code">
				  Motivo: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div>			        
			</div>			
			<div class="col-md-4">
				Descripci&oacute;n: <textarea class="form-control" rows="3"></textarea>			        
			</div>
		</div>
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<button type="button" class="btn btn-outline btn-success btn-lg btn-block" onclick="">Guardar</button>
			</div>
			<div class="col-md-4"></div>
		</div>		
    </div>
</div>
