<h1 class="page-header">Reporte Avanzado de Agencias</h1>
<div class="row">
	<div class="col-md-10">
	</div>
	<div class="col-md-2" align="right">
		<a class="btn btn-info" href="#busqueda-avanzada" data-toggle="collapse">Seleccionar Par&aacute;metros </a>
		<br/><br/>
	</div>	
</div>
<form id="form-busqueda-agencia"  class="form-busqueda-agencia" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
	<div id="busqueda-avanzada" class="collapse">
		<div class="row">
			<div class="col-md-10">
				<div class="input-group">
				  	<label>Nombre Agencia</label>
				  	<?= $this->form->nombre ?>
				</div>	
			</div>
			<div class="col-md-2">
				  	<label>RFC</label>
				  	<?= $this->form->rfc ?>	
			</div>	
		</div>
		<br/>
		<div class="row">
			<div class="col-md-10">
				<div class="input-group">
				  	<label>Nombre Comercial</label>
				  	<?= $this->form->nombre_comercial ?>
				</div>	
			</div>
			<div class="col-md-2">
				  	<label>Estatus</label>
				  	<?= $this->form->estatus ?>
			</div>	
		</div>
		<br/><hr class="hrForm">
		<div class="row">
			<div class="col-md-4">
				<div class="form-group input-group">
		            <label>Ciudad</label>
		           	<?= $this->form->ciudad ?>
		    	</div>
			</div>
			<div class="col-md-4">
				<div class="form-group input-group">
		            <label>Estado</label>
		           	<?= $this->form->estado ?>
		    	</div>
			</div>
			<div class="col-md-4">
				<div class="form-group input-group">
		            <label>C.P.</label>
		           	<?= $this->form->cp ?>
		    	</div>							
			</div>
		</div>			
		<br/><hr class="hrForm">
		<div class="row">
			<div class="col-md-4">
				<div class="form-group input-group">
		        	<label>Contacto Agencia</label>
		           	<?= $this->form->contacto ?>
		    	</div>
			</div>
			<div class="col-md-4">
				<div class="form-group input-group">
		            <label>Email</label>
		           	<?= $this->form->email ?>
		    	</div>
			</div>
			<div class="col-md-4">
				<div class="form-group input-group">
		            <label>Ejecutivo Asignado</label>
		           	<?= $this->form->ejecutivo ?>
		    	</div>
			</div>
		</div>	
		<br/><hr class="hrForm">
		<div class="row">
			<div class="col-md-3">
				<label>Productos Comprados:</label>
			</div>			    	
			<div class="col-md-6">
				<?= $this->form->licencias ?>
			</div>
			<div class="col-md-3">
				
			</div>			    		
		</div>
		<br/><hr class="hrForm">
		<br/>
		<div class="row">
			<div class="col-md-9"></div>			    	
			<div class="col-md-3">
				<button type="button" class="btn btn-block btn-outline btn-success" id="action-form-agencia" onclick="submitFormBusquedaAgencia()" href="#busqueda-avanzada" data-toggle="collapse">Buscar</button>		
			</div>		    		
		</div>
	</div>
</form>		

<br/>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-agencias">
	<thead>
		<tr>
			<th>ID Agencia</th>
			<th>Clave</th>
			<th>Nombre</th>
			<th>Direcci&oacute;n</th>
			<th>CP</th>
			<th>Ciudad</th>
			<th>Tel&oacute;fono</th>
			<th>Email</th>
		</tr>
	</thead>
	<tbody align="center">
	</tbody>
</table>