<h1 class="page-header">Reporte Clientes Por Producto</h1>

<div class="row">
	<div class="col-md-10">
		<div class="input-group">
		  	<label>Buscar por Producto</label> <?= $this->selectAgencias->select_agencias?>
		</div>
	</div>
</div>
<br/>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-agencias">
	<thead>
		<tr>
			<th>ID Agencia</th>
			<th>Clave</th>
			<th>Nombre</th>
			<th>Direcci&oacute;n</th>
			<th>CP</th>
			<th>Ciudad</th>
			<th>Tel&oacute;fono</th>
			<th>Email</th>			
		</tr>
	</thead>
	<tbody align="center">
	</tbody>
</table>

