<h1 class="page-header">Administraci&oacute;n de productos.</h1>
<div class="row">
	<div class="col-md-10"></div>
	<div class="col-md-2" align="right">
		<button type="button" class="btn btn-primary btn-circle"
			data-dismiss="modal" onclick="" data-toggle="modal"
			data-target="#myModal">
			&nbsp;<i class="fa fa-plus"></i>&nbsp;<i class="fa fa-user"></i>&nbsp;
		</button>
	</div>
</div>
<br />
<table width="100%"
	class="table table-striped table-bordered table-hover"
	id="dataTable-productos">
	<thead>
		<tr>
			<th>ID</th>
			<th>Clave</th>
			<th>Nombre</th>
			<th>Vigente</th>
			<th>Detalles</th>
		</tr>
	</thead>
	<tbody align="center">
			<?php foreach ($this->registros as $registro) { ?>
			<tr id='<?php echo $registro['id_producto'] ?>'
			<?php
			if ($registro ['vigente_prod'] == 0) {
				echo 'class="bg-warning"';
			}
			?>>
			<td><?php echo $registro['id_producto'] ?></td>
			<td><?php echo $registro['clave'] ?></td>
			<td><?php echo $registro['nombre_prod'] ?></td>
			<td>
				<?php
				if ($registro ['vigente_prod'] == 'S') {
					echo 'Activo';
				} else {
					echo 'Inactivo';
				}
				?>
			</td>
			<td>
				<button type="button" class="btn btn-primary btn-sm btn-circle"
					data-toggle="modal" data-target="#myModal"
					value='<?= json_encode($registro) ?>'
					onclick="datosform_edita_usuario(this.value)">
					<i class="fa fa-info-circle"></i>
				</button>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<br/>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">

     <div class="modal-header">
     	<div class="row">
    		<div class="col-md-10">
				<h4 class="modal-title" id="myModalLabel"></h4>
    		</div>
    		<div class="col-md-2" align="right">
       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
    		</div> 			    		
    	</div>
       

     </div>

     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">

	    <div class="modal-body">
			<fieldset>
				<legend>Datos del Producto:</legend>
				<div class="row">
		    		<div class="col-md-2">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Clave</label>
										<?= $this->form->clave ?>
								</div>
					        </div>
					    </div>			    		
		    		</div>	
		    		<div class="col-md-8">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Nombre del Producto</label>
										<?= $this->form->nombre_prod ?>
								</div>
					        </div>
					    </div>			    		    			    		
		    		</div>
		    		<div class="col-md-2">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Versi&oacute;n</label>
										<?= $this->form->version_prod ?>
								</div>
					        </div>
					    </div>	    		
		    		</div>		    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-12">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Ruta</label>
										<?= $this->form->ruta_prod ?>
								</div>
					        </div>
					    </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Cargo</label>
										<?= $this->form->cargo_prod ?>
								</div>
					        </div>
					    </div>	
		    		</div>
		    		<div class="col-md-6">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Compila</label>
										<?= $this->form->compila_prod ?>
								</div>
					        </div>
					    </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
					    <div class="form-group">
					        <div class="row">
					            <div class="col-xs-12">
					                <label class="control-label">Vigente</label>
										<?= $this->form->vigente_prod ?>
								</div>
					        </div>
					    </div>	
		    		</div>
		    		<div class="col-md-6">		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">  		
		    		</div>	    			    		
		    	</div>
			</fieldset>
	    </div>
	    <div class="modal-footer">     
	       <button type="button" class="btn btn-primary btn-circle btn-lg" ><i class="fa fa-edit"></i></button>
	       <span id="submitBtn" type="button" class="btn btn-success btn-circle btn-lg" onclick="submitForm()"><i class="fa fa-save"></i></span>
	       <button type="button" class="btn btn-danger btn-circle btn-lg" ><i class="fa fa-trash-o"></i></button>
	    </div>
     </form>
   </div>
 </div>
</div>