<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">
<link rel="stylesheet" type="text/css" href="public/css/orden-seguimiento/index.css">
<link rel="stylesheet" type="text/css" href="public/css/daterangepicker.css">
<script type="text/javascript" src="public/js/moment.js"></script>
<script type="text/javascript" src="public/js/daterangepicker.js"></script>
<form class="form-inline" method="get" name="filtroform" id="filtroform">
<?= $this->formUpdate->fecha_de ?>         
<?= $this->formUpdate->fecha_hasta ?>
<div class="row">
	<div class="col-md-2">
		<?= $this->formUpdate->id_agencia ?>
	</div>
	<div class="col-md-1">
		<?= $this->formUpdate->id_usuario_solicita?>
	</div>	
	
	<div class="col-md-2">
		<?= $this->formUpdate->daterange?>
	</div>
	<div class="col-md-2">
		<?= $this->formUpdate->Filtrar?>
	</div>
</div>
</form>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<caption>Historico de Actualizaciones.</caption>
			<thead>
				<tr>
					<th>Id</th>
					<th>Agencia</th>
					<th>Producto</th>
					<th>Usuario Solicita</th>
					<th>Fecha solicitud</th>
					<th>Fecha Cierre</th>
					<th>Usuario Atiende</th>
					<th>Versión</th>
					<th>Archivo</th>
					<th>Descripcion</th>
					<th>Editar</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $this->actualizacionesPendientes as $values ) {	?>
				<tr>
					<th scope="row"><?= $values['id_update'] ?></th>
					<td><?= $values['nombre'] ?></td>
					<td><?= $values['nombre_prod'] ?></td>
					<td><?= $values['nombre_usuario_solicita'] ?></td>
					<td><?= $values['fecha_solicitud'] ?></td>
					<td><?= $values['fecha_cierre'] ?></td>
					<td><?= $values['nombre_usuario_cierra'] ?></td>
					<td><?= $values['version_update'] ?></td>
					<td><?= $values['archivo_update'] ?></td>
					<td><?= $values['descripcion'] ?></td>
					<td><a class='btn btn-primary btn-xs' href="public/actualizaciones/editar/id_update/<?= $values['id_update'] ?>">Editar</a></td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<script>
$(function() {
    $('input[name="daterange"]').daterangepicker({ 
    	autoUpdateInput: false,
        locale: {
        format: 'YYYY-MM-DD'},
	    "applyLabel": "Aplicar",
	    "cancelLabel": "Limpiar",
	    "fromLabel": "De",
	    "toLabel": "Hasta",
	    "customRangeLabel": "Custom",
	    "daysOfWeek": [
	        "Do",
	        "Lu",
	        "Ma",
	        "Mi",
	        "Ju",
	        "Vi",
	        "Sa"
	    ],
	    "monthNames": [
	        "Enero",
	        "Febrero",
	        "Marzo",
	        "Abril",
	        "Mayo",
	        "Junio",
	        "Julio",
	        "Agusto",
	        "Septiembre",
	        "Octubre",
	        "Noviembre",
	        "Diciembre"
	    ]
    }, function(start, end, label) {
       // console.log("New date range selected: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
		$("#fecha_de").val(start.format('YYYY-MM-DD'));
		$("#fecha_hasta").val(end.format('YYYY-MM-DD'));
    });

    $('input[name="daterange"]').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
    });

    $('input[name="daterange"]').on('cancel.daterangepicker', function(ev, picker) {
		$("#fecha_de").val('');
		$("#fecha_hasta").val('');
        
        $(this).val('');
        
    });
    
});
</script>