
<h1 class="page-header">MIG</h1>

	<form method="post" enctype="application/x-www-form-urlencoded">
	<div class="row">
		<div class="col-md-3">
			<?= $this->formulario->id_agencia?>
		</div>
		<div class="col-md-3">
			<?= $this->formulario->id_usuario_soporte_titular?>
		</div>	
		<div class="col-md-3"><br>
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-primary form-control input-sm" data-toggle="modal" data-target="#productos-modal-filtro">
			  <i class="fa fa-list" aria-hidden="true"></i>
			  Filtro por productos
			</button>
			
			<!-- Modal -->
			<div class="modal fade" id="productos-modal-filtro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Filtro por productos</h4>
			      </div>
			      <div class="modal-body">
					<?= $this->formulario->productos?>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			
			      </div>
			    </div>
			  </div>
			</div>
		</div>
		
	
	</div>
	<br>
	<div class="row">
		<div class="col-md-3">
			<?= $this->formulario->clave_ciudad?>
		</div>
		<div class="col-md-3">
			<?= $this->formulario->prov_timbrado?>
		</div>
			
	</div>
	<div class="row">
		<div class="col-md-12">
				<?= $this->formulario->Filtrar?>
		</div>
	</div>
	</form>

<br>
<div class="well">
<h2>Resultados: <?php echo count( $this->agencias ) ?> Agencia(s).</h2>
<p>Nota: Muestra máximo 100 resultados.</p>
</div>
<p>
<?php 
	if (isset($this->params['productos'])) { ?>
		Productos en el filtro: <b>
		<?php  foreach ($this->params['productos'] as $param) { 
			$prod = new Application_Model_DbTable_Producto();
			?>
		<?= strtoupper( $prod->find($param)->toArray()[0]['clave'] ).',' ?>
	<?php } ?>
		</b>
	<?php }?>
</p>

<?php if ( isset($this->agencias) ) { ?>
<div class="row">
	<?php foreach ($this->agencias as $agencia) { ?>
	<div class="row">	
		<div class="col-md-12">
			<h1><?= $agencia['nombre'] ?> [<?= $agencia['clave'] ?>]
			<a  class="btn btn-info" href="<?= $this->baseUrl() ?>/agencias/index/id_agencia/<?= $agencia['id_agencia'] ?>" target="_blank"> Ir a Configuración de la Agencia</a></h1>
			<br>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-3">
			<p><label>RFC: </label> <?= $agencia['rfc'] ?></p>			
			<p><label>Dirección: </label> <?= $agencia['direccion'] ?></p>
			<p><label>Colonia: </label> <?= $agencia['colonia'] ?></p>
			<p><label>C.P.: </label> <?= $agencia['cp'] ?></p>
			<p><label>Clave de Ciudad: </label> <?= $agencia['clave_ciudad'] ?></p>
			<label>Teléfonos: </label>
			<p><?= $agencia['tel1'] ?></p>
			<p><?= $agencia['tel2'] ?></p>
			<br>
			<label>Emails: </label>
			<p><?= $agencia['email'] ?></p>
			<p><?= $agencia['email_alt'] ?></p>
		</div>
		<div class="col-md-3">
			<p><label>Password B.D.: </label> <?= $agencia['dba_pwd'] ?></p>
			<p><label>Prov. Timbrado: </label> <?= $agencia['prov_timbrado'] ?></p>
			<p><label>Titular de Soporte: </label> <?= $agencia['soporte_titular_nombre'] ?></p>
			<p><label>Auxiliar de Soporte: </label> <?= $agencia['soporte_auxiliar_nombre'] ?></p>
			<p><label>Factura Eletrónica: </label> <?= $agencia['factura_electronica'] ?></p>
			<p><label>URL PFE: </label><br>
			 <a href="http://fe.icaavwin.com.mx/public/login/user/id/<?= $agencia['id_agencia'] ?>" id="url-portal-fe-agencia" style="color: black;" target="_new" >http://fe.icaavwin.com.mx/public/login/user/id/<?= $agencia['id_agencia'] ?></a>
			 </p>
			
										
			
			
		</div>
		<div class="col-md-6">
			<h4>Productos</h4>
			<table class="table table-striped">
			<thead><tr>
				<th>Clave</th>
				<th>Producto</th>
				<th>Estatus</th>
				<th>Licencias</th>
			
			</tr></thead>
			<tbody>
			<?php foreach ( $agencia['productos_agencia'] as $productos ) { ?>
				<tr>
					<td><?= $productos['clave'] ?></td>
					<td><?= $productos['nombre_prod'] ?></td>
					<td><?= $productos['estatus'] ?></td>
					<td><?= $productos['numero_licencias'] ?></td>
				</tr>
			<?php }?>
			</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h4>Polizas Vigentes</h4>
			<table class="table table-striped">
			<thead><tr>
				<th>Clave</th>
				<th>Nombre Producto</th>
				<th>Tipo</th>
				<th>Fecha Inicio</th>
				<th>Fecha Fin</th>
				<th>Horas</th>
				<th>Horas consumidas</th>
				<th>Estatus</th>
			</tr></thead>
			<tbody>
			<?php foreach ( $agencia['polizas_agencia'] as $polizas ) { ?>
				<tr>
					<td><a class="btn btn-info" target="_new" href="<?= $this->baseUrl() ?>/orden-seguimiento/consultar-ordenes-por-poliza/id_poliza/<?= $polizas['id_poliza']?>"> <?= $polizas['clave_poliza'] ?></a></td>
					<td><?= $polizas['nombre_prod'] ?></td>
					<td><?= $polizas['descripcion_tipo_poliza'] ?></td>
					<td><?= $polizas['fecha_ini'] ?></td>
					<td><?= $polizas['fecha_fin'] ?></td>
					<td><?= $polizas['horas_poliza'] ?></td>
					<td><?= $polizas['horas_consumidas'] ?></td>
					<td><?= $polizas['descripcion_poliza_estatus'] ?></td>
				</tr>
			<?php }?>
			</tbody>
			</table>
			
		</div>
		<div class="col-md-6">
			
		</div>
	</div>
	<hr>
	<?php } ?>
</div>

<?php } ?>
