<h1 class="page-header">MIG</h1>
<form method="post" enctype="application/x-www-form-urlencoded">
<div class="row">
	<div class="col-md-2">
		<?= $this->formulario->id_agencia?>
	</div>
	<div class="col-md-2">
		<?= $this->formulario->id_usuario_soporte_titular?>
	</div>	
		<div class="col-md-1">
		<?= $this->formulario->Filtrar?>
	</div>	
</div>
</form>
<br>
<?php if ( isset($this->agencias) ) { ?>
<div class="row">
	<?php foreach ($this->agencias as $agencia) { ?>
	<div class="row">	
		<div class="col-md-12">
			<h1><?= $agencia['nombre'] ?> [<?= $agencia['clave'] ?>]</h1><br>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-3">
			<p><label>RFC: </label> <?= $agencia['rfc'] ?></p>			
			<p><label>Dirección: </label> <?= $agencia['direccion'] ?></p>
			<p><label>Colonia: </label> <?= $agencia['colonia'] ?></p>
			<p><label>C.P.: </label> <?= $agencia['cp'] ?></p>
			<p><label>Clave de Ciudad: </label> <?= $agencia['clave_ciudad'] ?></p>
			<label>Teléfonos: </label>
			<p><?= $agencia['tel1'] ?></p>
			<p><?= $agencia['tel2'] ?></p>
			<br>
			<label>Emails: </label>
			<p><?= $agencia['email'] ?></p>
			<p><?= $agencia['email_alt'] ?></p>
		</div>
		<div class="col-md-3">
			<p><label>Password B.D.: </label> <?= $agencia['dba_pwd'] ?></p>
			<p><label>Prov. Timbrado: </label> <?= $agencia['prov_timbrado'] ?></p>
			<p><label>Titular de Soporte: </label> <?= $agencia['soporte_titular_nombre'] ?></p>
			<p><label>Auxiliar de Soporte: </label> <?= $agencia['soporte_auxiliar_nombre'] ?></p>
			<p><label>Factura Eletrónica: </label> <?= $agencia['factura_electronica'] ?></p>
		</div>
		<div class="col-md-6">
			<h4>Productos</h4>
			<table class="table table-striped">
			<thead><tr>
				<th>Clave</th>
				<th>Nombre Producto</th>
				<th>Estatus</th>
				<th>Numero Licencias</th>
			
			</tr></thead>
			<tbody>
			<?php foreach ( $agencia['productos_agencia'] as $productos ) { ?>
				<tr>
					<td><?= $productos['clave'] ?></td>
					<td><?= $productos['nombre_prod'] ?></td>
					<td><?= $productos['estatus'] ?></td>
					<td><?= $productos['numero_licencias'] ?></td>
				</tr>
			<?php }?>
			</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<h4>Polizas Vigentes</h4>
			<table class="table table-striped">
			<thead><tr>
				<th>Clave</th>
				<th>Nombre Producto</th>
				<th>Tipo</th>
				<th>Fecha Inicio</th>
				<th>Fecha Fin</th>
				<th>Horas</th>
				<th>Horas consumidas</th>
			</tr></thead>
			<tbody>
			<?php foreach ( $agencia['polizas_agencia'] as $polizas ) { ?>
				<tr>
					<td><?= $polizas['clave_poliza'] ?></td>
					<td><?= $polizas['nombre_prod'] ?></td>
					<td><?= $polizas['tipo'] ?></td>
					<td><?= $polizas['fecha_ini'] ?></td>
					<td><?= $polizas['fecha_fin'] ?></td>
					<td><?= $polizas['horas_poliza'] ?></td>
					<td><?= $polizas['horas_consumidas'] ?></td>
				</tr>
			<?php }?>
			</tbody>
			</table>
		</div>
	</div>
	<hr>
	<?php } ?>
</div>
<a  class="btn btn-info" href="<?= $this->baseUrl() ?>/agencias/index/id_agencia/<?= $agencia['id_agencia'] ?>" target="_blank"> Detalles</a>
<?php } ?>