<?php if ($this->guardado == 0 ){?>
<button class="btn btn-primary btn-xs" type="submit" onclick="goBack()">Regresar</button>
<br>
<br>
<?php } ?> 
<div class="panel panel-default">
	<div class="panel-heading">Editar Registro</div>
	<div class="panel-body">
	<?php if ($this->guardado == 0 ){?>
		<?php include 'form_registro.phtml';?>
		<input type="hidden" id="clave_municipio_aux" value="<?php echo $this->clave_municipio ?>">
		<?php } else { ?>
			<div class="alert alert-success" role="alert">Actualizado Correctamente.</div>
			<a class="btn btn-primary btn-lg" href="<?= $this->baseUrl() ?>/index/seguimiento" role="button">Volver a Seguimiento</a>
		<?php } ?>
	</div>
</div>

<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['id_rol'] ==2) {?>
<script type="text/javascript">
//$("#form :input").attr("disabled", true);
</script>
<?php }?>