<div class="panel panel-default">
  <div class="panel-heading">Filtrar Resultados</div>
  <div class="panel-body">
	<form class="form-inline" method="get" name="filtroform" id="filtroform">
		<div class="row">
				<div class="col-md-3">
					<div class="form-group">
					<label class="" for="">Estatus</label><br>
        			<?php echo $this->formFiltro->seguimiento?>
		   			 </div>
				</div>

				<div class="col-md-3">
				 <div class="form-group">
			       <label class="" for="">Ap. Paterno</label><br>
			       <?php echo $this->formFiltro->apellido_paterno?>
			    </div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
			       <label class="" for="">Ap. Materno</label><br>
			       <?php echo $this->formFiltro->apellido_materno?>
			    </div>
			 </div>
			<div class="col-md-3">
			 	<div class="form-group">
			       <label class="" for="">Nombre</label><br>
			       <?php echo $this->formFiltro->nombre?>
			    </div>	
			</div>

		</div>
		<br>
		<div class="row">
				<div class="col-md-2">
				 	<div class="form-group">
				       <label class="" for="">Id</label><br>
				       <?php echo $this->formFiltro->id_registro_personas?>
				    </div>	
				</div>
				<div class="col-md-2">
					<div class="form-group">
						<label class="" for="">Fecha de Registro</label><br>
     					 <?php echo $this->formFiltro->fecharegistro?>
   					 </div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label class="" for="">Estado en M&eacute;xico</label><br>
      					 <?php echo $this->formFiltro->estado?>
   					 </div>
				</div>
				<div class="col-md-2">
					<div class="form-group">
			     	  <label class="" for="">Estado en USA</label><br>
			      	 <?php echo $this->formFiltro->estado_eu?>
		   			 </div>
				</div>
			<div class="col-md-2">
			 	<div class="form-group">
			       <?php echo $this->formFiltro->filtrar?>
			    </div>	
			</div>
		</div>
	  </form>
</div>			
  
</div>

<pre>Se muestran <?php echo $this->countArray ?> resultados</pre>


<table class="table table-bordered">
  <thead>
  	<tr>
  	<th>ID</th>
  	<th>Nombre Completo</th>
  	<th>Estado</th>
  	<th>Municipio o Localidad</th>
  	<th>Estado USA</th>
  	<th>Fecha de Registro</th>
  	<th>Estatus de Seguimiento</th>
  	<th>Acciones</th>
  	</tr>
  </thead>
  <tbody>
  
  <?php foreach ($this->paginator as $registro) { ?>
  <?php switch ( $registro['id_seguimiento']){
  	case 1:
  		$css_class = 'class=""';
  		break;
  	case 2:
  		$css_class = 'class="active"';
  		break;
  	case 3:
  		$css_class = 'class="danger"';
  		break;
  		}
  		
  
  ?>
 
  <tr <?php echo $css_class ?>>
  	<td><?php echo $registro['id_registro_personas'] ?></td>
  	<td><?php echo $registro['apellido_paterno'].' '.$registro['apellido_materno'].' '.$registro['nombre'] ?></td>
  	<td><?php echo $registro['nombre_entidad'] ?></td>
  	<td><?php echo $registro['nombre_municipio'] ?></td>
  	<td><?php echo $registro['estado'] ?></td>
  	<td><?php 
   	$date= new Zend_Date($registro['fecha_registro'] ,('yyyy-MM-dd')); 
  	$fecha =  $date->toString("dd").' de '.$date->toString("MMMM, yyyy");
  	echo $fecha;
  	
  	
  	?></td>
  	<td><?php echo $registro['seguimiento'] ?></td>
  	<td>
  	<?php if ( $registro['id_seguimiento'] == 1 ) {?>
  	<a href="<?= $this->baseUrl() ?>/index/modificaregistro?id_registro_personas=<?php echo $registro['id_registro_personas'] ?>">
  	<button type="button" class="btn btn-default  btn-xs" aria-label="Left Align">
	 <i class="fa fa-pencil-square-o"></i>
	</button>
	</a>
  	<?php } else { ?>
  <?php if ($_SESSION['Zend_Auth']['USER_VALUES']['id_rol'] ==1) {?>
    <a href="<?= $this->baseUrl() ?>/index/modificaregistro?id_registro_personas=<?php echo $registro['id_registro_personas'] ?>">
  	<button type="button" class="btn btn-default  btn-xs" aria-label="Left Align">
	 <i class="fa fa-pencil-square-o"></i>
	</button>
	</a>
  <?php } ?>
  
  
  	<a href="<?= $this->baseUrl() ?>/index/consultaregistro?id_registro_personas=<?php echo $registro['id_registro_personas'] ?>">
  	<button type="button" class="btn btn-default  btn-xs" aria-label="Left Align">
		<i class="fa fa-info"></i>
	</button>
	</a>
  	<?php } ?>
  	</td>
  </tr>
  <?php } ?>
  </tbody>
  <tfoot>
</table>


<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>

