<h1 class="page-header">Reporte Servicios Por Ejecutivos</h1>

<div class="row">
	<div class="col-md-10">
		<div class="input-group">
		  	<label>Buscar Ejecutivo:</label> <?= $this->selectAgencias->select_agencias?>
		</div>
	</div>
</div>
<br/>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-servicios-clientes">
	<thead>
		<tr>
			<th>ID Orden</th>
			<th>Producto</th>
			<th>Fecha Solicitud</th>
			<th>Fecha Respuesta</th>
			<th>Duraci&oacute;n</th>
			<th>Solicit&oacute;</th>
			<th>Agencia</th>			
			<th>Conformidad</th>
		</tr>
	</thead>
	<tbody align="center">
	</tbody>
</table>