<h1 class="page-header">Nueva Orden de Servicio</h1>
<div class="input-group">

	<div class="row">
		  	<label>Buscar Agencia:</label>
		  	<?= $this->selectAgencias->select_agencias?>
	</div>
		<div class="row">
		  	<label>Tipo Soporte:</label>
		  	<?= $this->selectAgencias->tipo_soporte?>
	</div>

</div>
		<?= $this->render('/orden-creacion/render/datosAgencia.phtml') ?>
		<?= $this->render('/orden-creacion/render/servicio.phtml') ?>

