<!-- Modal -->
<div class="modal fade" id="modalNuevoProducto" tabindex="-1" role="dialog" aria-labelledby="modalNuevoProducto">
	<div class="modal-dialog modal-md" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="row">
					<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabelProducto">Nuevo Producto</h4>
					</div>
					<div class="col-md-2" align="right">
							<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
					</div> 			    		
				</div>
			</div>
	 		<form method="post" id="formProducto">
	 			<?= $this->formProductos->id_producto_formProducto ?> 
			    <div class="modal-body">
					<fieldset>
						<div class="row">
				    		<div class="col-md-12" id="nombre_prod_div">
								<div class="form-group">
									<label class="control-label">Producto</label>
									<?= $this->formProductos->nombre_prod ?>
								</div>
				    		</div>	    			    		
				    	</div>
				    	<div class="row" align="center">
				    		<div class="col-md-6" id="numero_licencias_div">
								<div class="form-group">
					                <label class="control-label"> N&uacute;mero de licencias </label>
					                <?= $this->formProductos->numero_licencias ?>
					            </div>
				    		</div>
				    		<div class="col-md-6">
								<div class="form-group">
									<label class="control-label">Estado</label>
									   <?= $this->formProductos->estatus_producto ?>
								</div>
				    		</div>	    			    		
				    	</div>
				    </fieldset>
			    </div>
			    <div class="modal-footer"> 
			    	<div class="row">
						<div class="col-md-3"></div>			    	
			    		<div class="col-md-6">
			       			<span id="submitFormProductoBtn" type="button" class="btn btn-block btn-outline btn-success" onclick="submitFormProducto()">Guardar</span>			
			    		</div>
						<div class="col-md-3"></div>			    		
			    	</div>	  		        
			    </div>
	 		</form> 
		</div>
	</div>
</div>