<!-- Modal -->
<div class="modal fade" id="modalNuevaPoliza" tabindex="-1" role="dialog" aria-labelledby="modalNuevaPoliza">
	<div class="modal-dialog" role="document">
	   	<div class="modal-content">
		    <div class="modal-header">
		     	<div class="row">
		    		<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
		    		</div>
		    		<div class="col-md-2" align="right">
		       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
		    		</div> 			    		
		    	</div>
		    </div>
		    <form method="post" id="formPoliza"> 
		      	<input type="hidden" name="edita_id_user" id="edita_id_user">
		      	<input name="accion" value="editar" type="hidden">

			    <div class="modal-body">
					<fieldset>
						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Producto</label>
									<?= $this->formPolizas->producto ?>
									<!-- <select></select> -->
								</div>
				    		</div>	    			    		
				    	</div>
						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Tipo de P&oacute;liza</label>
									<?= $this->formPolizas->tipo ?>
								</div>
				    		</div>	    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-6">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-clock-o"></i>
					                </span>
					                <?= $this->formPolizas->horas_poliza ?>
					            </div>
				    		</div> 			    		
				    		<div class="col-md-6">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-list-alt"></i>
					                </span>
					               <?= $this->formPolizas->costo_poliza ?> 
					            </div>
				    		</div> 			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-6">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-play"></i>
					                </span>
					               <?= $this->formPolizas->fecha_ini ?>  
					            </div>
				    		</div>
				    		<div class="col-md-6">
								<div class="form-group input-group">
						        	<span class="input-group-addon"><i class="fa fa-stop"></i></span>
						        	<?= $this->formPolizas->fecha_fin ?>  
					            </div>	    		
				    		</div>	    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-12">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-bookmark-o"></i></span>
					               	<?= $this->formPolizas->estatus_poliza ?> 
					            </div>
				    		</div>    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-12">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Observaciones</i>
					                </span>
					               	<?= $this->formPolizas->observaciones_poliza ?> 
					            </div>
				    		</div>  			    		
				    	</div>		    			    	
					</fieldset>
			    </div>
			    <div class="modal-footer">  
			    	<div class="row">
						<div class="col-md-3"></div>			    	
			    		<div class="col-md-6">
			       			<span id="submitPolizaBtn" type="button" class="btn btn-block btn-outline btn-success" onclick="">Guardar</span>	    			
			    		</div>
						<div class="col-md-3"></div>			    		
			    	</div>
			    </div>
		 	</form>
	   	</div>
 	</div>
</div>