<!-- Modal -->
<div class="modal fade" id="modalNuevaPoliza" tabindex="-1" role="dialog" aria-labelledby="modalNuevaPoliza">
	<div class="modal-dialog" role="document">
	   	<div class="modal-content">
		    <div class="modal-header">
		     	<div class="row">
		    		<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabel">P&oacute;liza</h4>
		    		</div>
		    		<div class="col-md-2" align="right">
		       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
		    		</div> 			    		
		    	</div>
		    </div>
		    <form method="post" id="formPoliza"> 
		      	<input type="hidden" name="edita_id_user" id="edita_id_user">
		      	<input name="accion" value="editar" type="hidden">

			    <div class="modal-body">
					<fieldset>
						<div class="row">
				    		<div class="col-md-6">
								<div class="form-group">
									<label class="control-label">Producto</label>
									<?= $this->formPolizas->producto ?>
									<!-- <select></select> -->
								</div>
				    		</div>	    			    		
				    	
				    		<div class="col-md-6">
								<div class="form-group">
									<label class="control-label">Tipo de P&oacute;liza</label>
									<?= $this->formPolizas->tipo ?>
								</div>
				    		</div>	    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-6">
								<div class="form-group">
					                <label class="control-label">Horas</label>
					                </span>
					                <?= $this->formPolizas->horas_poliza ?>
					            </div>
				    		</div> 			    		
				    		<div class="col-md-6" id="div-costo-poliza">
								<div class="form-group input-group">
					               <label class="control-label">Importe de la P&oacute;liza</label>
					               <?= $this->formPolizas->costo_poliza ?> 
					            </div>
				    		</div> 			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-6">
								<div class="form-group input-group">
					                <label class="control-label">Fecha de Inicio</label>
					                <p id="fecha_ini_txt"></p>
					               <?= $this->formPolizas->fecha_ini ?>  
					            </div>
				    		</div>
				    		<div class="col-md-6">
								<div class="form-group input-group">
						            <label class="control-label">Fecha de T&eacute;rmino</label>
						            <p id="fecha_fin_txt"></p>
								   	<?= $this->formPolizas->fecha_fin ?>  
					            </div>	    		
				    		</div>	    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-6">
								<div class="form-group input-group">
					                <label class="control-label">Fecha Corte de Servicio</label>
					               <?= $this->formPolizas->fecha_fin_servicio ?>  
					            </div>
				    		</div>    			    		
				    	</div>
				    	<div class="row" id="div-id-poliza-estatus">
				    		<div class="col-md-12">
								<div class="form-group input-group">
					               <label class="control-label">Estatus</label>
					               	<?= $this->formPolizas->id_poliza_estatus ?> 
					            </div>
				    		</div>    			    		
				    	</div>
				    	<div class="row">
				    		<div class="col-md-12">
								<div class="form-group input-group">
					                <label class="control-label">Observaciones</label>
					               	<?= $this->formPolizas->observaciones_poliza ?> 
					            </div>
				    		</div>  			    		
				    	</div>		    			    	
					</fieldset>
			    </div>
			    <div class="modal-footer">  
			    	<div class="row">
						<div class="col-md-3"></div>			    	
			    		<div class="col-md-6">
			       			<span id="submitPolizaBtn" type="button" class="btn btn-block btn-outline btn-success" onclick="">Guardar</span>	    			
			    		</div>
						<div class="col-md-3"></div>			    		
			    	</div>
			    </div>
		 	</form>
	   	</div>
 	</div>
</div>