<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
 	<div class="modal-dialog modal-lg" role="document">
   		<div class="modal-content">
		<!--    <div class="modal-header">
		     	<div class="row">
		    		<div class="col-lg-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
		    		</div>
		    		<div class="col-lg-2" align="right">
		       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
		    		</div> 			    		
		    	</div>
		    </div>-->
		    
		         <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
		    
		    
		    <div class="modal-body modal-body-agencia">
	           	<div class="panel-body">
	     
	           		<form id="form_agregar_agencia">
	           		<?= $this->form->id_agencia ?>
	            	<div class="panel with-nav-tabs panel-primary">
		                <div class="panel-heading">
		                        <ul class="nav nav-tabs">
		                            <li class="active"><a href="#tabGenerales" data-toggle="tab">Datos Generales</a></li>
		                            <li><a href="#tabConfiguraciones" data-toggle="tab">Configuraciones</a></li>
		                        </ul>
		                </div>
		                <div class="panel-body container-fluid">
		                    <div class="tab-content">
		                        <div class="tab-pane fade in active" id="tabGenerales">
								    <div class="form-group">
								        <div class="row">
								            <div class="col-xs-6">
								                <label class="control-label">Nombre de la Agencia</label>
								                <?= $this->form->nombre ?>
								            </div>
								            <div class="col-xs-6">
								                <label class="control-label">Nombre Comercial</label>
								                <?= $this->form->nombre_comercial ?>
								            </div>
								        </div>
								    </div>						    
								    <div class="form-group">
								        <div class="row">
								            <div class="col-xs-4">
								                <label class="control-label">Clave de la Agencia</label>
								                <?= $this->form->clave ?>
								            </div>
								            <div class="col-xs-4">
								                <label class="control-label">RFC</label>
								                <?= $this->form->rfc ?>
								            </div>
								            <div class="col-xs-4">
								                <label class="control-label">Sucursales</label>
								                <?= $this->form->sucursales ?>
								            </div>
								        </div>
								    </div>
									<div class="row">
										<div class="col-md-12 well">
											<h4 class="h4Form">Direcci&oacute;n</h4>
											<hr class="hrForm">
											<div class="row">
												<div class="col-md-6">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Calle y Número</label>
																	<?= $this->form->direccion ?>
															</div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Colonia</label>
												                <?= $this->form->colonia ?>
												            </div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-2">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">C&oacute;digo Postal</label>
												                <?= $this->form->cp ?>
												            </div>
												        </div>
												    </div>													
												</div>
											</div>
											<!-- <div class="row">
												<div class="col-md-6">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Municipio</label>
															</div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Estado</label>

												            </div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-2">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Pais</label>

												            </div>
												        </div>
												    </div>													
												</div>
											</div>	-->										
										</div>
									</div>
									<div class="row">
										<div class="col-md-12">
											<h4 class="h4Form">Contacto</h4>
											<hr class="hrForm">
											<div class="row">
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-phone"></i> Teléfono Principal</label>
												                <?= $this->form->tel1 ?>
												            </div>
												        </div>
												    </div>											
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-phone"></i> Teléfono Alterno</label>
												                <?= $this->form->tel2 ?>
												            </div>
												        </div>
												    </div>  											
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-globe"></i> Sitio Web</label>
												                <?= $this->form->http ?>
												            </div>
												        </div>
												    </div>  											
												</div>
											</div>										
										</div>
									</div>
									<div class="row">
										<div class="col-md-4">
										    <div class="form-group">
										        <div class="row">
										            <div class="col-xs-12">
										                <label class="control-label"><i class="fa fa-envelope-o"></i> Principal</label>
										                <?= $this->form->email ?>
										            </div>
										        </div>
										    </div>											
										</div>
										<div class="col-md-4">
										    <div class="form-group">
										        <div class="row">
										            <div class="col-xs-12">
										                <label class="control-label"><i class="fa fa-envelope-o"></i> Alterno</label>
										                <?= $this->form->email_alt ?>
										            </div>
										        </div>
										    </div>												
										</div>
									</div>
								</div>
		                        <div class="tab-pane fade" id="tabConfiguraciones">
									
		                        	<div class="row">
										<div class="col-md-12">
											<div class="row">
		                        				<div class="col-lg-3">
													<div class="form-group">
														<label class="control-label">Login Update</label>
														<?= $this->form->update_login ?>
													</div>
		                        				</div>
		                        				<div class="col-lg-3">
													<div class="form-group">
										                <label class="control-label">Password Update</label>
														<?= $this->form->update_pwd ?> 
													</div>
		                        				</div>
		                        				<div class="col-lg-3">
													<div class="form-group">
														<label class="control-label">Login BD</label>
														<?= $this->form->update_login_bd ?>
													</div>
		                        				</div>
		                        				<div class="col-lg-3">
													<div class="form-group">
										                <label class="control-label">Password BD</label>
														<?= $this->form->update_pwd_bd ?> 
													</div>
		                        				</div>
		                        			</div>	
										</div>
									</div>
								     <div class="row">
							    		<div class="col-lg-3">
							        	<label class="control-label">Ejecutivo Titular</label>
							        	<?= $this->form->id_usuario_soporte_titular ?>
							    		</div>
									    <div class="col-lg-3">
									        <label class="control-label">Ejecutivo Auxiliar</label>
									         <?= $this->form->id_usuario_soporte_auxiliar ?>
									    </div>
									</div>
									<h4 class="h4Form">IATAS</h4>
									<hr class="hrForm">
									<div class="row">
										<div class="col-md-2">
									        <label class="control-label">IATA 1</label>
									        <?= $this->form->iatas1 ?>				
										</div>
										<div class="col-md-2">
									        <label class="control-label">IATA 2</label>
									        <?= $this->form->iatas2 ?>				
										</div>
										<div class="col-md-2">
									        <label class="control-label">IATA 3</label>
									        <?= $this->form->iatas3 ?>				
										</div>
										<div class="col-md-2">
									        <label class="control-label">IATA 4</label>
									        <?= $this->form->iatas4 ?>				
										</div>
										<div class="col-md-2">
									        <label class="control-label">IATA 5</label>
									        <?= $this->form->iatas5 ?>				
										</div>
									</div>	
									<h4 class="h4Form">Datos de Conexión</h4>
									<hr class="hrForm">
									<div class="row">
										<div class="col-md-2">
									        <?= $this->form->nombre_bd ?>				
										</div>
										<div class="col-md-2">
									        <?= $this->form->host ?>				
										</div>
										<div class="col-md-2">
									        <?= $this->form->puerto ?>				
										</div>
										<div class="col-md-2">
									        <?= $this->form->data_source_name ?>				
										</div>
										<div class="col-md-4">
									        <?= $this->form->observaciones_conexion ?>				
										</div>
									</div>	
		                        </div>	                        
		                    </div>
		                </div>
		            </div>
		            </form>
	           </div>
	        </div>
	      	<div class="modal-footer"> 
		    	<div class="row">
					<div class="col-md-9"></div>			    	
					<div class="col-md-3">
						<button type="button" class="btn btn-success" id="action-form-agencia">Guardar</button>
					</div>			    		
		    	</div>
		    </div>
   		</div>
 	</div>
</div>


