<!-- Modal -->
<div class="modal fade" id="nuevoUsuarioModal" tabindex="-1" role="dialog" aria-labelledby="nuevoUsuarioModal">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="row">
					<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
					</div>
					<div class="col-md-2" align="right">
							<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
					</div> 			    		
				</div>
			</div>
 		<form method="post" id="formUsuarioAgencia"> 
		  	<input type="hidden" name="edita_id_user" id="edita_id_user">
		  	<input name="accion" value="editar" type="hidden">

		    <div class="modal-body">
				<fieldset>
					<h4 class="h4Form">Datos Personales</h4>
					<hr class="hrForm">
					<div class="row">
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-user"></i>
				                </span>
				                  <?= $this->formUsuarioAgencia->nombreUsuarioAgencia ?>
				               <!--  <input type="text" class="form-control" placeholder="Nombre"> -->
				            </div>
			    		</div>	    			    		
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-user"></i>
				                </span>

										<?= $this->formUsuarioAgencia->apellidos ?>
				           <!--     <input type="text" name="apellidos" id="apellidos" autocomplete="off" class="form-control" maxlength="225" placeholder="Apellidos"> -->
				            </div>
			    		</div>
<!-- 			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-user"></i>
				                </span>
				                <input type="text" class="form-control" placeholder="Apellido Materno">
				            </div>	    		
			    		</div>    -->			    		
			    	</div>
			    	<h4 class="h4Form">Contacto</h4>
					<hr class="hrForm">
					<div class="row">
			    		<div class="col-md-3">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-phone"></i>
				                </span>
				                <?= $this->formUsuarioAgencia->telefono ?>
				             <!--    <input type="text" class="form-control" placeholder="Telefono Contacto"> -->
				            </div>
			    		</div>	    			    		
			    		<div class="col-md-2">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-tags"></i>
				                </span>
				               <!-- No existe en la BD -->
				                <input disabled type="text" class="form-control" placeholder="Ext.">
				            </div>
			    		</div>
			    		<div class="col-md-3">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-mobile"></i>
				                </span>

				                <input  disabled type="text" class="form-control" placeholder="Celular">
				            </div>	    		
			    		</div>  
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-envelope-o"></i>
				                </span>
				                 <?= $this->formUsuarioAgencia->emailUsuarioAgencia ?>
				              <!--   <input type="text" class="form-control" placeholder="Correo"> -->
				            </div>	    		
			    		</div>  			    		 			    		
			    	</div>
			    	<h4 class="h4Form">Puesto</h4>
					<hr class="hrForm">			    	
					<div class="row">
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Puesto</label>
								   <?= $this->formUsuarioAgencia->puesto ?>
				               <!--  <input type="text" class="form-control" placeholder="Puesto"> -->
							</div>
			    		</div>	    			    		
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Director</label>
								 <?= $this->formUsuarioAgencia->director ?>
							</div>
			    		</div>
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Lider de Proyecto</label>
								 <?= $this->formUsuarioAgencia->lider_proy ?>
							</div>   		
			    		</div>   			    		
			    	</div>
			    	<h4 class="h4Form">Credenciales de Acceso</h4>
					<hr class="hrForm">
			    	<div class="row">
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-user"></i>
				                </span>
				                 <?= $this->formUsuarioAgencia->clave ?>
				               <!--  <input type="text" class="form-control" placeholder="Clave"> -->
				            </div>
			    		</div>			    	
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-lock"></i>
				                </span>
				                     <?= $this->formUsuarioAgencia->pwd ?>
				               <!--  <input type="text" class="form-control" placeholder="Contraseña"> -->
				            </div>
			    		</div>
			    		<div class="col-md-4">
							<div class="form-group input-group">
				                <span class="input-group-addon"><i class="fa fa-lock"></i>
				                </span>
				                         <?= $this->formUsuarioAgencia->pwd_conf?>
				                <!-- <input type="text" class="form-control" placeholder="Confirmar Contraseña"> -->
				            </div>	    		
			    		</div>	    			    		
			    	</div>
				</fieldset>
				<fieldset>
					<h4 class="h4Form">Permisos</h4>
					<hr class="hrForm">
			    	<div class="row">
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Admin Fe</label>
	  									<?= $this->formUsuarioAgencia->admin_fe?>
							</div>
			    		</div>
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Enviar Reporte MIG</label>
									<?= $this->formUsuarioAgencia->enviar_reporte_portal_mig?>
							</div>   		
			    		</div>	    			    		
			    		<div class="col-md-4">
							<div class="form-group">
								<label class="control-label">Bajar Actualizaciones</label>
									<?= $this->formUsuarioAgencia->bajar_updates?>
							</div> 
			    		</div>    			    		
			    	</div>
			    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon">Estatus</span>
			                <?= $this->formUsuarioAgencia->activo ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	</fieldset>
		    </div>
		    <div class="modal-footer">     
		       <button type="button" class="btn btn-primary btn-circle btn-lg" ><i class="fa fa-edit"></i></button>
		       <span id="submitNuevoUsuarioAgenciaBtn" type="button" class="btn btn-success btn-circle btn-lg" onclick="submitFormUsuarioAgencia()"><i class="fa fa-save"></i></span> 
		       <button type="button" class="btn btn-danger btn-circle btn-lg" ><i class="fa fa-trash-o"></i></button>
		    </div>
 		 </form> 
		</div>
	</div>
</div>