<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
 	<div class="modal-dialog modal-lg" role="document">
   		<div class="modal-content">
		    <div class="modal-header">
		     	<div class="row">
		    		<div class="col-lg-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
		    		</div>
		    		<div class="col-lg-2" align="right">
		       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
		    		</div> 			    		
		    	</div>
		    </div>
		    <div class="modal-body" style="padding-top: 0px;">
	           	<div class="panel-body" style="padding-top: 0px;padding-left: 0px;padding-bottom: 0px; padding-right: 0px;">
	     
	           		<form id="form_agregar_agencia">
	           		<?= $this->form->id_agencia ?>
	            	<div class="panel with-nav-tabs panel-primary">
		                <div class="panel-heading">
		                        <ul class="nav nav-tabs">
		                            <li class="active"><a href="#tabGenerales" data-toggle="tab">Datos Generales</a></li>
		                            <li><a href="#tabConfiguraciones" data-toggle="tab">Configuraciones</a></li>
		                        </ul>
		                </div>
		                <div class="panel-body">
		                    <div class="tab-content">
		                        <div class="tab-pane fade in active" id="tabGenerales">
								    <div class="form-group">
								        <div class="row">
								            <div class="col-xs-12">
								                <label class="control-label">Nombre de la Agencia</label>
								                <?= $this->form->nombre ?>
								            </div>
								        </div>
								    </div>
								    <div class="form-group">
								        <div class="row">
								            <div class="col-xs-12">
								                <label class="control-label">Nombre Comercial</label>
								                <?= $this->form->nombre_comercial ?>
								            </div>
								        </div>
								    </div>								    
								    <div class="form-group">
								        <div class="row">
								            <div class="col-xs-4">
								                <label class="control-label">Clave de la Agencia</label>
								                <?= $this->form->clave ?>
								            </div>
								            <div class="col-xs-4">
								                <label class="control-label">RFC</label>
								                <?= $this->form->rfc ?>
								            </div>
								            <div class="col-xs-4">
								                <label class="control-label">Sucursales</label>
								                <?= $this->form->sucursales ?>
								            </div>
								        </div>
								    </div>
									<div class="row">
										<div class="col-md-12 well">
											<h4 class="h4Form">Direcci&oacute;n</h4>
											<hr class="hrForm">
											<div class="row">
												<div class="col-md-6">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Direcci&oacute;n</label>
																	<?= $this->form->direccion ?>
															</div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Colonia</label>
												                <?= $this->form->colonia ?>
												            </div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-2">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">C&oacute;digo Postal</label>
												                <?= $this->form->cp ?>
												            </div>
												        </div>
												    </div>													
												</div>
											</div>
											<div class="row">
												<div class="col-md-6">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Municipio</label>
															</div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Estado</label>

												            </div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-2">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label">Pais</label>

												            </div>
												        </div>
												    </div>													
												</div>
											</div>											
										</div>
									</div>
									<div class="row">
										<div class="col-md-12">
											<h4 class="h4Form">Contacto</h4>
											<hr class="hrForm">
											<div class="row">
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-phone"></i> Principal</label>
												                <?= $this->form->tel1 ?>
												            </div>
												        </div>
												    </div>											
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-phone"></i> Alterno</label>
												                <?= $this->form->tel2 ?>
												            </div>
												        </div>
												    </div>  											
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-globe"></i> Sitio Web</label>
												                <?= $this->form->http ?>
												            </div>
												        </div>
												    </div>  											
												</div>
											</div>										
										</div>
									</div>
									<div class="row well">
										<div class="col-md-12">
											<h4 class="h4Form">Correos</h4>
											<hr class="hrForm">
											<div class="row">
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-envelope-o"></i> Principal</label>
												                <?= $this->form->email ?>
												            </div>
												        </div>
												    </div>											
												</div>
												<div class="col-md-4">
												    <div class="form-group">
												        <div class="row">
												            <div class="col-xs-12">
												                <label class="control-label"><i class="fa fa-envelope-o"></i> Alterno</label>
												                <?= $this->form->email ?>
												            </div>
												        </div>
												    </div>												
												</div>
												<div class="col-md-4">
												
												</div>
											</div>											
										</div>
									</div>
								</div>
		                        <div class="tab-pane fade" id="tabConfiguraciones">
		                   
									<h4 class="h4Form">Acceso</h4>
									<hr class="hrForm">
		                        	<div class="row">
										<div class="col-md-12">
		                        			<div class="row">
		                        				<div class="col-lg-5">
													<div class="form-group">
														<label class="control-label">Login Update</label>
														<?= $this->form->update_login ?>
													</div>
		                        				</div>
		                        				<div class="col-lg-5">
													<div class="form-group">
										                <label class="control-label">Password Update</label>
														<?= $this->form->update_pwd ?> 
													</div>
		                        				</div>
		                        				<div class="col-lg-2">
													<div class="form-group">
										                <label class="control-label">Modificar</label>
										                <select class="form-control">
										                    <option value="1">Si</option>
										                    <option value="0">No</option>
										                </select>
													</div>		                        				
		                        				</div>		                        				
		                        			</div>
										</div>
									</div>
									<h4 class="h4Form">Ejecutivos</h4>
									<hr class="hrForm">
									<div class="row">
										<div class="col-md-12">
										<div class="form-group">
										<div class="row">
										    <div class="col-xs-6">
										        <label class="control-label">Ejecutivo Titular</label>
										        <?= $this->form->cve_usopor_tit ?>
										    </div>

										    <div class="col-xs-6">
										        <label class="control-label">Ejecutivo Auxiliar</label>
										         <?= $this->form->cve_usopor_aux ?>
										    </div>
										</div>
										</div>												
										</div>
									</div>										                        	
		                        </div>	                        
		                    </div>
		                </div>
		            </div>
		            </form>
	           </div>
	        </div>
	      	<div class="modal-footer">     
		       <button type="button" class="btn btn-success btn-circle btn-lg" id="action-form-agencia"><i class="fa fa-save"></i></button>
		    </div>
   		</div>
 	</div>
</div>


