<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">

<h1 class="page-header">Seguimiento Ordenes de Servicio Admin</h1>


<div class="row">
	<table width="100%" class="table">
		<thead>
			<tr>
				<th class="amarillo centrado">Lamada sin Contestar</th>
				<th class="naranja centrado">Reportarse</th>
				<th class="rojo centrado">Reportarse Urgente</th>
				<th class="centrado">Otros Servicios</th>
				<th class="morado centrado">Externos</th>
				<th class="verde centrado">Atendiendose</th>		
			</tr>
		</thead>	
	</table>
</div>
<br/>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-servicios-clientes">
	<thead>
		<tr>
			<th class="centrado">ID Orden</th>
			<th class="centrado">Fecha Solicitud</th>
			<th class="centrado">Producto</th>
			<th class="centrado">Agencia</th>			
			<th class="centrado">Solicit&oacute;</th>
			<th class="centrado">Atendio</th>			
			<th class="centrado">Motivo</th>
			<th class="centrado">Duraci&oacute;n</th>
			<th class="centrado">Info</th>
		</tr>
	</thead>
	<tbody align="center">
		<?php foreach ($this->registros as $registro) { ?>
		<tr id='<?php echo $registro['id_orden_servicio'] ?>'
		<?php if($registro['estatus_reloj']!=0){
			echo 'class="verde"';
			}else{
				switch ($registro['id_orden_servicio_estatus']) {
				    case "1":echo 'class="amarillo"';break;
				    case "2":echo 'class="naranja"';break;
				    case "3":echo 'class="rojo"';break;
				    case "4":echo 'class=""';break;
				    case "5":echo 'class="morado"';break;
				    default:echo 'class=""';
				}
			} ?>
		>
			<td><?php echo $registro['id_orden_servicio'] ?></td>
			<td><?php echo $registro['fecha_alta'] ?></td>
			<td><?php echo $registro['producto'] ?></td>
			<td style="font-size: smaller !important;"><?php echo $registro['nombre_agencia'] ?></td>
			<td><?php echo $registro['nombre_usuario'].' '.$registro['apellidos_usuario'] ?></td>
			<td><?php echo $registro['nombre_atiende'].' '.$registro['apellido_paterno'] ?></td>
			<td><?php echo $registro['motivo'] ?></td>
			<td><?php echo $registro['duracion_servicio'] ?></td>
			<td>
				<button type="button" class="btn btn-primary btn-sm btn-circle"
					data-toggle="modal" data-target="#myModal"
					value='<?= json_encode($registro) ?>'
					onclick="datosform_edita_orden(this.value)">
					<i class="fa fa-info-circle"></i>
				</button>				
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
	<div class="modal-dialog modal-md" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="row">
					<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
					</div>
					<div class="col-md-2" align="right">
							<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
					</div> 			    		
				</div>
			</div>
	 		<form method="post" id="formProducto"> 
			    <div class="modal-body">
					<fieldset>
						<h4 id="titulo_form_producto" class="h4Form">Informaci&oacute;n Servicio</h4>
						<hr class="hrForm">

						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Producto</label>
									<?= $this->formOrdenes->producto ?>
								</div>
				    		</div>	    			    		
				    	</div>
				    	<div class="row">
				    		
				    		<div class="col-md-12">
								<div class="form-group">
					                <label class="control-label"> Solicit&oacute; </label>
					                <?= $this->formOrdenes->solicito ?>
					                  
					            </div>
				    		</div>
				    		
				    	</div>   
						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Atendio</label>
									   <?= $this->formOrdenes->ejecutivo ?>
								</div>
				    		</div>	    			    		
				    	</div>
						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Duraci&oacute;n del Servicio</label>
									   <?= $this->formOrdenes->duracion ?>
								</div>
				    		</div>	    			    		
				    	</div>				    	
						<div class="row">
				    		<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Cancelar</label>
									<span id="cancelarBoton" type="button" class="btn btn-block btn-outline btn-danger" onclick="submitCancelarOrden()">Cancelar Orden</span>	
								</div>
				    		</div>	    			    		
				    	</div>     			    		
				    </fieldset>
			    </div>
			    <div class="modal-footer"> 
			    	<div class="row">
						<div class="col-md-3"></div>			    	
			    		<div class="col-md-6">
			       			<span id="submitFormProductoBtn" type="button" class="btn btn-block btn-outline btn-success" onclick="submitFormProducto()">Actualizar Orden</span>			
			    		</div>
						<div class="col-md-3"></div>			    		
			    	</div>	  		        

			    </div>
	 		</form> 
		</div>
	</div>
</div>



