<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">

<h1 class="page-header">Seguimiento Ordenes de Servicio Admin</h1>


<div class="row">
	<table width="100%" class="table">
		<thead>
			<tr>
				<th class="amarillo">Lamada sin Contestar</th>
				<th class="naranja">Reportarse</th>
				<th class="rojo">Reportarse Urgente</th>
				<th class="">Otros Servicios</th>
				<th class="morado">Externos</th>
				<th class="verde">Atendiendose</th>		
			</tr>
		</thead>	
	</table>
</div>

<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-servicios-clientes">
	<thead>
		<tr>
			<th>ID Orden</th>
			<th>Fecha Solicitud</th>
			<th>Producto</th>
			<th>Solicit&oacute;</th>
			<th>Agencia</th>
			<th>Atendio</th>			
			<th>Motivo</th>
			<th>Info</th>
		</tr>
	</thead>
	<tbody align="center">
		<?php foreach ($this->registros as $registro) { ?>
		<tr id='<?php echo $registro['id_orden_servicio'] ?>'
		<?php if($registro['estatus_reloj']!=0){
			echo 'class="verde"';
			}else{
				switch ($registro['id_orden_servicio_estatus']) {
				    case "1":echo 'class="amarillo"';break;
				    case "2":echo 'class="naranja"';break;
				    case "3":echo 'class="rojo"';break;
				    case "4":echo 'class=""';break;
				    case "5":echo 'class="morado"';break;
				    default:echo 'class=""';
				}
			} ?>
		>
			<td><?php echo $registro['id_orden_servicio'] ?></td>
			<td><?php echo $registro['fecha_alta'] ?></td>
			<td><?php echo $registro['producto'] ?></td>
			<td style="font-size: smaller !important;"><?php echo $registro['nombre_agencia'] ?></td>
			<td><?php echo $registro['nombre_usuario'].' '.$registro['apellidos_usuario'] ?></td>
			<td><?php echo $registro['nombre_atiende'].' '.$registro['apellido_paterno'] ?></td>
			<td><?php echo $registro['motivo'] ?></td>
			<td>
				<button type="button" class="btn btn-primary btn-sm btn-circle"
					data-toggle="modal" data-target="#myModal"
					value='<?= json_encode($registro) ?>'
					onclick="datosform_edita_orden(this.value)">
					<i class="fa fa-info-circle"></i>
				</button>				
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>