<label for="asterisco">Campos obligatorios *</label>
		<form id="form" name="form" method="post">
			<div class="form-group">
				<label for="apellido_paterno">Apellido Paterno:</label>
				<?php echo $this->form->apellido_paterno?>
			</div>
			<div class="form-group">
				<label for="apellido_materno">Apellido Materno:</label> 
					<?php echo $this->form->apellido_materno?>
			</div>
			<div class="form-group">
				<label for="nombre">Nombre(s)*:</label>
					<?php echo $this->form->nombre?>
			</div>
			<div class="form-group inline">
				<label for="fechanacimiento">Fecha de Nacimiento*:</label>
				<?php echo $this->form->fechanacimiento?>
			</div>
			<div class="form-group">
				<label for="email">Email*:</label>
					<?php echo $this->form->email?>
			</div>
			<div class="form-group">
				<label for="estado">Estado:</label>	
					<?php echo $this->form->estado?>
			</div>
			<div class="form-group">
				<label for="apellido_paterno">Municipio o Delegaci&oacute;n:</label>
					<?php echo $this->form->mun_del?>
			</div>
			<div class="form-group">
				<label for="genero">G&eacute;nero:</label>
				<div class="radio">
					<?php echo $this->form->genero?>
				</div>
			</div>
			<div class="form-group">
				<label for="escolaridad">Escolaridad:</label>
				<div class="radio">
					<?php echo $this->form->escolaridad?>
				</div>
			</div>
			<div class="form-group">
				<label for="ocupacion">Ocupaci&oacute;n:</label>
				<?php echo $this->form->ocupacion?>
			</div>
			<div class="form-group">
				<label for="estado_eu">Estado de E.U.A. Donde Radica:</label>
				<?php echo $this->form->estado_eu?>
			</div>
			<div class="form-group">
				<label for="radica">Lugar Donde Radica Actualmente:</label>
				<?php echo $this->form->radica?>
			</div>
			<div class="form-group">
				<label for="tiempo_radicar">Tiempo de Radicar en Estados Unidos:</label>
				<label>A&ntilde;o(s):<?php echo $this->form->tiempo_radicar_anio?></label>
				<label>Mes(es):<?php echo $this->form->tiempo_radicar_meses?></label>
			</div>
			<div class="form-group">
				<label for="tel_contacto">Tel&eacute;fono de Contacto:</label>
				<div class="form-group">
					<label>Casa:<?php echo $this->form->tel_contacto_casa?></label>
					<label>Celular:<?php echo $this->form->tel_contacto_celular?></label>
					<label>Trabajo:<?php echo $this->form->tel_contacto_trabajo?></label>
				</div>
			</div>
			<div class="form-group">
				<label for="cuenta_registro">&#191;Cuenta con registro de
					nacimiento?:</label>
				<div class="radio">
					<?php echo $this->form->cuenta_registro?>
				</div>
			</div>
			<div class="form-group">
				<label for="sabe_donde_nacio">Si no cuenta con registro de
					nacimiento, sabe usted:</label>
				<div class="radio">
					<?php echo $this->form->sabe_donde_nacio?>
				</div>
				<div class="form-group" id="donde_nacio_otro_div">
					<label>
						<?php echo $this->form->donde_nacio_otro?>
					</label>
				</div>
			</div>
			<div class="form-group">
				<label for="descripcion">Descripci&oacute;n breve del problema o
					caso:(Manifestar lo que desea y su problema actual, si es un
					tercero, favor de mencionarlo)<?php echo $this->form->desc_problema?>
				</label>
			</div>
			<div class="form-group">
				<label for="descripcion">&#191;Cuenta con los siguientes documentos?: </label>
				<div class=checkbox>
					<?php echo $this->form->cuenta_documentos?>
				</div>
				<div class="form-group" id="cuenta_documentos_otro_div">
					<label>
						<?php echo $this->form->cuenta_documentos_otro?>
					</label>
				</div>
			</div>
			<div class="form-group">
				<label for="cuenta_con_personas_aux">&#191;Cuenta con personas que
					le puedan auxiliar en tr&aacute;mites en su lugar de origen?(En
					caso de que si, preguntar si existe v&iacute;nculo familiar y
					qui&eacute;nes ser&iacute;an.) </label>
				<div class=checkbox>
					<label> 						
					<?php echo $this->form->si_cuenta_con_personas_aux?>Si
					</label>
				</div>
				<?php echo $this->form->desc_cuenta_con_persona?>
			</div>
			<?php echo $this->form->guardar?>
		</form>