  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Bienvenido, ingrese sus credenciales.</h3>
          </div>
          <div class="panel-body">
            <form  class="form-signin" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
              <fieldset>
                <div class="form-group">
                  <?php echo $this->form->username;?>
                </div>
                <div class="form-group">
                  <?php echo $this->form->password;?>
                </div>
                <?php if ( $this->error != ''){?>
                  <div class="alert alert-danger" role="alert"><?= $this->error ?></div>
                <?php }?>
                <?php echo $this->form->submit;?>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>