  
      <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Identificarse</h3>
                    </div>
                    <div class="panel-body">
			            <form  class="form-signin" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
                            <fieldset>
                                <div class="form-group">
                                    <?php echo $this->form->username;?>
                                </div>
                                <div class="form-group">
					                <?php echo $this->form->password;?>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                     <?php echo $this->form->submit;?>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>