
<script>

/**
 * 
 * @param elementName
 * @param minutes
 * @param seconds
 */function countdown( elementName, minutes, seconds )
{
    var element, endTime, hours, mins, msLeft, time;

    function twoDigits( n )
    {
        return (n <= 9 ? "0" + n : n);
    }

    function updateTimer()
    {
        msLeft = endTime - (+new Date);

        if ( msLeft < 1000 ) {
            element.innerHTML = "0:00";
            //location.reload(); 
        } else {
            time = new Date( msLeft );
            
            
            hours = time.getUTCHours();
            mins = time.getUTCMinutes();
            
           /* if(twoDigits( time.getUTCSeconds()) == '20' &&  twoDigits( mins )=='00' ){
            	$('.btn_submit4').remove();
            	$( "#dialog-message-end" ).dialog( "open" );
            }*/
            
            element.innerHTML = (hours ? hours + ':' + twoDigits( mins ) : mins) + ':' + twoDigits( time.getUTCSeconds() );
            setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
        }
    }

    element = document.getElementById( elementName );
    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
    updateTimer();
}
 /*
$( document ).ready(function() {
	 $( "#dialog-message-end" ).dialog({
	     modal: true,
	     autoOpen: false,
	     buttons: {
	       Ok: function() {
	         $( this ).dialog( "close" );
	         location.reload(); 
	       }
	     },
	     close: function( event, ui ) {
	    	 location.reload(); 
	     }
	   });
	 $( "#dialog-message-start" ).dialog({
	     modal: true,
	     autoOpen: false,
	     buttons: {
	       Ok: function() {
	         $( this ).dialog( "close" );
	       }
	     }
	   });
});
*/

	$( document ).ready(function() {
		countdown( "countdown", 0, <?= $this->secondsRemaining ?> ); // [id],[Min],[Seg].
		//$( "#dialog-message-start" ).dialog( "open" );



		var clock = $('.your-clock').FlipClock({
		// ... your options here
		});
	});

</script>
Vista

<span id='countdown' class="countdown-banamex"></span>






		<link rel="stylesheet" href="<?= $this->baseUrl() ?>/js/flipclock/flipclock.css">

		
		<script src="<?= $this->baseUrl() ?>/js/flipclock/flipclock.min.js"></script>

		<div class="your-clock"></div>

