<style>
	th, td {
    	padding-top: 5px !important;
    	padding-bottom: 5px !important;
	}
	.panel-heading {
    	padding-top: 7px !important;
    	padding-bottom: 7px !important;
	}
</style>


<br/>
<?php $titulo=1;?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <center>Monitoreo de Llamadas</center>
    </div>
    <div class="panel-body">

<?php foreach ($this->ordenes as $ordenes) { ?>
	<?php if($titulo==1){?>
		<div class="row">
	<?php }?>
	<div class="col-md-4 tablaMonitoreo2" style="height:270px;">
		<div class="panel panel-info" style="height:270px;">
		    <div class="panel-heading">
		    	<?php $num=1; foreach ($ordenes as $solicitud) { ?>
		        	<center><?php echo $solicitud['nombre_atiende'].' '.$solicitud['apellido_paterno'] ?></center>
		        	<?php break; ?>
		        <?php } ?>
		    </div>
		    <div class="panel-body tablaMonitoreo">
				<div class="table-responsive" style="height:270px; overflow: auto;">
					<table width="100%" class="table table-striped table-bordered table-hover fz2">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>			
								<th>Agencia</th>
								<th>Solicito</th>
								<th>Reporte</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($ordenes as $solicitud) { ?>
							<tr id='<?php echo $solicitud['id_orden_servicio'] ?>'
								<?php
									if($solicitud['estatus_reloj']!=0){
										echo 'class="verde"';
									}else{								
										switch ($solicitud['id_orden_servicio_estatus']) {
										    case "1":echo 'class="amarillo"';break;
										    case "2":echo 'class="naranja"';break;
										    case "3":echo 'class="rojo"';break;
										    case "4":echo 'class=""';break;
										    case "5":echo 'class="morado"';break;
										    default:echo 'class=""';
										}
									}
								?>
							>
								<td><?php echo $num; $num++; ?></td>
								<td><?php echo $solicitud['fecha_alta'] ?></td>
								<td><?php echo $solicitud['nombre_agencia'] ?></td>
								<td><?php echo $solicitud['nombre_usuario'].' '.$solicitud['apellidos_usuario'] ?></td>
								<td><?php echo $solicitud['id_orden_servicio'] ?></td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
		    </div>
		</div>
	</div>
	<?php if($titulo==3){?>
		</div>
	<?php $titulo=1;}else{$titulo++;} ?>	
<?php } ?>	
	</div>
</div>
<div class="row">
	<div class="col-md-12 alert alert-info marquee">
	    <div class='marquee-text'>
	        <h4 id="toptitle" style="margin-bottom: 0px;"><b>Testing this marquee function</b></h4>
	    </div>
	</div>	
</div>




<script type="text/javascript">
	$(document).ready(function() { 
		var marquee = $('div.marquee');

		marquee.each(function() {
		    var mar = $(this),indent = mar.width();
		    mar.marquee = function() {
		        indent--;
		        mar.css('text-indent',indent);
		        if (indent < -1 * mar.children('div.marquee-text').width()) {
		            indent = mar.width();
		        }
		    };
		    mar.data('interval',setInterval(mar.marquee,900/60));
		});
		var info="";
		$.ajax({
		  url      : document.location.protocol + '//ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=10&callback=?&q=' + encodeURIComponent('http://feeds.abcnews.com/abcnews/travelheadlines'),
		  dataType : 'json',
		  success  : function (data) {
		    if (data.responseData.feed && data.responseData.feed.entries) {
		      $.each(data.responseData.feed.entries, function (i, e) {
		        info+="--"+"title: " + e.title+"--"+"author: " + e.author;
		      });
		      $("#toptitle").text(info);		    }
		  }
		});
	}); // end  $(document).ready(function() { 
</script>
