<meta http-equiv="refresh" content="20"> 

<style>
	th, td {
    	padding-top: 5px !important;
    	padding-bottom: 5px !important;
	}
	.panel-heading {
    	padding-top: 7px !important;
    	padding-bottom: 7px !important;
	}
</style>
<!-- 
<meta http-equiv="refresh" content="5; url=http://merca.mig.com.mx">
 -->
<br/>
<?php $titulo=1;?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <center>Monitoreo de Llamadas</center>
    </div>
    <div class="panel-body">

<?php foreach ($this->ordenes as $key => $ordenes) { ?>
	<?php if($titulo==1){?>
		<div class="row">
	<?php }?>
	<div class="col-md-4 tablaMonitoreo2">
		<div class="panel panel-info">
		    <div class="panel-heading">
		    	<?php $num=1;?>
		        	
		        	<center><b><?php echo $this->usuariosAdminNombres[$key]  ?></b></center>
		        	
		        
		    </div>
		    <div class="panel-body tablaMonitoreo">
				<div class="table-responsive" overflow: auto;">
					<table width="100%" class="table table-striped table-bordered table-hover fz2">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>			
								<th>Agencia</th>
								<th>Solicito</th>
								<th>Id O.S.</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($ordenes as $solicitud) { ?>
							<tr id='<?php echo $solicitud['id_orden_servicio'] ?>'
								<?php
									if($solicitud['estatus_reloj']!=0){
										echo 'class="verde"';
									}else{								
										switch ($solicitud['id_orden_servicio_estatus']) {
										    case "1":echo 'class="amarillo"';break;
										    case "2":echo 'class="naranja"';break;
										    case "3":echo 'class="rojo"';break;
										    case "4":echo 'class=""';break;
										    case "5":echo 'class="morado"';break;
										    default:echo 'class=""';
										}
									}
								?>
							>
								<td><?php echo $num; $num++; ?></td>
								<td><?php echo $solicitud['fecha_alta'] ?></td>
								<td><?php echo $solicitud['nombre_agencia'] ?></td>
								<td><?php echo $solicitud['nombre_usuario'].' '.$solicitud['apellidos_usuario'] ?></td>
								<td><?php echo $solicitud['id_orden_servicio'] ?></td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
		    </div>
		</div>
	</div>
	<?php if($titulo==3){?>
		</div>
	<?php $titulo=1;}else{$titulo++;} ?>	
<?php } ?>	
	</div>
</div>

