<br/>
<div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           <div class="panel-heading ">
	                <h1 class="page-header">Administraci&oacute;n de usuarios.</h1>
	           </div>
	           <div class="panel-body">
		           	<div class="row">
						<div class="col-md-10">
						</div>
						<div class="col-md-2" align="right">
						    <button type="button" class="btn btn-primary btn-circle" data-dismiss="modal" onclick="abrirModalAgregarUsuario()" data-toggle="modal" data-target="#myModal">
						    &nbsp;<i class="fa fa-plus"></i>&nbsp;<i class="fa fa-user"></i>&nbsp;
						    </button>
						</div>
					</div>
					<br/>
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre</th>
								<th>Estatus</th>
								<th>Correo</th>
								<th>Detalles</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->registros as $registro) { ?>
							<tr
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_usuario'] ?></td>
								<td><?php echo $registro['clave'] ?></td>
								<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 'S' ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td><?php echo $registro['email'] ?></td>
								<td>
									<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" value='<?= json_encode($registro) ?>'
									onclick="datosform_edita_usuario(this.value)">
									<i class="fa fa-info-circle"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<br/>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">

     <div class="modal-header">
     	<div class="row">
    		<div class="col-md-10">
				<h4 class="modal-title" id="myModalLabel"></h4>
    		</div>
    		<div class="col-md-2" align="right">
       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
    		</div> 			    		
    	</div>
       

     </div>

     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">

	    <div class="modal-body">
			<fieldset>
				<legend>Datos Generales:</legend>
				<div class="row">
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->clave ?>
			            </div>
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->nombre ?>
			            </div>
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->apellido_paterno ?>
			            </div>	    		
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->apellido_materno ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span>
			                <?= $this->form->pwd ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span>
			                <?= $this->form->pwd_conf ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-suitcase"></i>
			                </span>
			                <?= $this->form->puesto ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-envelope"></i>
			                </span>
			                <?= $this->form->email ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon">Estatus</span>
			                <?= $this->form->activo ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
			</fieldset>
			<fieldset>
				<legend>Permisos:</legend>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Admin</span>
			                <?= $this->form->admin ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Supervisor</span>
			                <?= $this->form->supervisor ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Folios</span>
			                <?= $this->form->folios ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Compila</span>
			                <?= $this->form->compila ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	    	</fieldset>
	    </div>
	    <div class="modal-footer">     
	       <button type="button" class="btn btn-primary btn-circle btn-lg" ><i class="fa fa-edit"></i></button>
	       <span type="button" class="btn btn-success btn-circle btn-lg" onclick="submitForm()"><i class="fa fa-save"></i></span>
	    </div>
     </form>
   </div>
 </div>
</div>
