 <h1 class="page-header">Administraci&oacute;n de usuarios.</h1>
   	<div class="row">
		<div class="col-md-10">
		</div>
		<div class="col-md-2" align="right">
	    <button type="button" class="btn btn-primary btn-circle" data-dismiss="modal" onclick="habilitaClave()" data-toggle="modal" data-target="#myModal">
	    &nbsp;<i class="fa fa-plus"></i>&nbsp;<i class="fa fa-user"></i>&nbsp;
	    </button>
	</div>
</div>
<br/>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
	<thead>
		<tr>
			<th>ID</th>
			<th>Username</th>
			<th>Nombre</th>
			<th>Estatus</th>
			<th>Correo</th>
			<th>Detalles</th>
		</tr>
	</thead>
	<tbody align="center">
		<?php foreach ($this->registros as $registro) {
				$registro['pwd']='';			 ?>
	<tr id='<?php echo $registro['id_usuario'] ?>'
		<?php 
			if ( $registro['activo'] == 0 ){
				echo 'class="bg-warning"';
			}
		?>
		>
		<td><?php echo $registro['id_usuario'] ?></td>
		<td><?php echo $registro['clave'] ?></td>
		<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
		<td>
		<?php 
			if ( $registro['activo'] == 'S' ){
			echo 'Activo';
			} else {
			echo 'Inactivo';
			}
		?>
		</td>
		<td><?php echo $registro['email'] ?></td>
		<td >
			<button type="button" class="btn btn-primary btn-sm btn-circle" data-toggle="modal" data-target="#myModal" value='<?= json_encode($registro) ?>'
			onclick="datosform_edita_usuario(this.value)">
			<i class="fa fa-info-circle"></i>
			</button>
		</td>
	</tr>
	<?php } ?>
	</tbody>
</table>
<br/>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">

     <div class="modal-header">
     	<div class="row">
    		<div class="col-md-10">
				<h4 class="modal-title" id="myModalLabel"></h4>
    		</div>
    		<div class="col-md-2" align="right">
       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
    		</div> 			    		
    	</div>
     </div>
     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">

	    <div class="modal-body">
			<fieldset>
				<legend>Datos Generales:</legend>
				<div class="row">
		    		<div class="col-md-8">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span> -->
			                <label>Usuario</label>
			                <?= $this->form->clave ?>
			            </div>
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group">
			                <!-- <span class="input-group-addon">Estatus</span> -->
			                <label>Estatus</label>
			                <?= $this->form->activo ?>
			            </div>	   
		    		</div>		    			    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-4">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span> -->
			                <label>Nombre</label>
			                <?= $this->form->nombre ?>
			            </div>
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span> -->
			                <label>Apellido Paterno</label>
			                <?= $this->form->apellido_paterno ?>
			            </div>	    		
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span> -->
			                <label>Apellido Materno</label>
			                <?= $this->form->apellido_materno ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span> -->
			                <label>Contraseña</label>
			                <?= $this->form->pwd ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span> -->
			                <label>Confirmar Contraseña</label>
			                <?= $this->form->pwd_conf ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-suitcase"></i>
			                </span> -->
			                <label>Puesto</label>
			                <?= $this->form->puesto ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group">
			                <!-- <span class="input-group-addon"><i class="fa fa-envelope"></i>
			                </span> -->
			                <label>Correo</label>
			                <?= $this->form->email ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
			</fieldset>
			<fieldset>
				<legend>Permisos:</legend>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Admin</label>
			                <?= $this->form->p_admin ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Supervisor</label>
			                <?= $this->form->p_supervisor ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Agregar Folios</label>
			                <?= $this->form->p_agrega_folios ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Ejecutivo</label>
			                <?= $this->form->p_ejecutivo ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Recepcionista</label>
			                <?= $this->form->p_recepcionista ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Ventas</label>
			                <?= $this->form->p_ventas ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Es ejecutivo</label>
			                <?= $this->form->es_ejecutivo ?>
			            </div>	   
		    		</div>   
		    		<div class="col-md-6">
						<div class="form-group">
			                <label>Edita Poliza</label>
			                <?= $this->form->p_edita_poliza ?>
			            </div>	    		
		    		</div>	 			    		
		    	</div>
	    	</fieldset>
	    </div>
	    <div class="modal-footer">     
	    	<div class="row">
				<div class="col-md-3"></div>			    	
	    		<div class="col-md-6">
	       			<span id="submitBtn" type="button" class="btn btn-block btn-outline btn-success" onclick="submitForm()">Guardar</span>    			
	    		</div>
				<div class="col-md-3"></div>			    		
	    	</div>
	    </div>
     </form>
   </div>
 </div>
</div>