<br/>

<div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           <div class="panel-heading ">
	                <h1 class="page-header">Administraci&oacute;n de usuarios.</h1>
	           </div>
	           <div class="panel-body">
		           	<div class="row">
						<div class="col-md-10">
						</div>
						<div class="col-md-2" align="right">
						    <button type="button" class="btn btn-primary btn-circle" data-dismiss="modal">&nbsp;<i class="fa fa-plus"></i>&nbsp;<i class="fa fa-user"></i>&nbsp;</button>
						</div>
					</div>
					<br/>
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre</th>
								<th>Estatus</th>
								<th>Correo</th>
								<th>Detalles</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->paginator as $registro) { ?>
							<tr
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_usuario'] ?></td>
								<td><?php echo $registro['clave'] ?></td>
								<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 'S' ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td><?php echo $registro['email'] ?></td>
								<td>
									<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal"
									onclick="datosform_edita_usuario('<?php echo $registro['id_usuario'] ?>','<?php echo $registro['clave'] ?>','<?php echo $registro['nombre'] ?>','<?php echo $registro['apellido_materno'] ?>','<?php echo $registro['apellido_paterno'] ?>','<?php echo $registro['activo'] ?>')">
									<i class="fa fa-info-circle"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<br/>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">

     <div class="modal-header">
     	<div class="row">
    		<div class="col-md-10">
				<h4 class="modal-title" id="myModalLabel"></h4>
    		</div>
    		<div class="col-md-2" align="right">
       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
    		</div> 			    		
    	</div>
       

     </div>

     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">
      	<div class="modal-footer" style="padding-top: 10px;padding-bottom: 0px;">     
	       <button type="button" class="btn btn-default btn-circle btn-lg" ><i class="fa fa-edit"></i></button>
	       <button type="button" class="btn btn-default btn-circle btn-lg" onclick="submitForm()"><i class="fa fa-save"></i></button>
	    </div>
	    <div class="modal-body" style="padding-top: 0px;">

	    	<h4 style="border-bottom: 2px solid #31708f;padding-bottom: 5px;">Datos Generales</h4>

	    	<div class="row">
	    		<div class="col-md-4">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-user"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Nombre" id="edita_nombre">
		            </div>
	    		</div>
	    		<div class="col-md-4">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-user"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Apellido Paterno" id="edita_apellido_paterno">
		            </div>	    		
	    		</div>
	    		<div class="col-md-4">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-user"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Apellido Materno" id="edita_apellido_materno">
		            </div>	    		
	    		</div>	    			    		
	    	</div>

	    	<div class="row">
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-lock"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Nueva Contrase&ntilde;a" id="edita_password">
		            </div>
	    		</div>
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-lock"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Confirmar Nueva Contrase&ntilde;a" id="edita_passwordConfirm">
		            </div>	    		
	    		</div>	    			    		
	    	</div>

	    	<div class="row">
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-suitcase"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Puesto" id="edita_puesto">
		            </div>
	    		</div>
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon"><i class="fa fa-envelope"></i>
		                </span>
		                <input type="text" class="form-control" placeholder="Email" id="edita_email">
		            </div>	    		
	    		</div>	    			    		
	    	</div>

	    	<div class="row">
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon">Estatus</span>
		                <select class="form-control" id="edita_activo" name="edita_activo">
					    	<option value="1">Activo</option>
					    	<option value="0">Inactivo</option>
					   </select>
		            </div>	    		
	    		</div>	    			    		
	    	</div>

	    	<h4 style="border-bottom: 2px solid #31708f;padding-bottom: 5px;">Permisos</h4>

	    	<div class="row">
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon" style="min-width: 150px;">Admin</span>
		                <select class="form-control" id="edita_activo" name="edita_activo">
					    	<option value="1">Activo</option>
					    	<option value="0">Inactivo</option>
					   </select>
		            </div>	   
	    		</div>
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon" style="min-width: 150px;">Supervisor</span>
		                <select class="form-control" id="edita_activo" name="edita_activo">
					    	<option value="1">Activo</option>
					    	<option value="0">Inactivo</option>
					   </select>
		            </div>	    		
	    		</div>	    			    		
	    	</div>
	    	<div class="row">
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon" style="min-width: 150px;">Folios</span>
		                <select class="form-control" id="edita_activo" name="edita_activo">
					    	<option value="1">Activo</option>
					    	<option value="0">Inactivo</option>
					   </select>
		            </div>	   
	    		</div>
	    		<div class="col-md-6">
					<div class="form-group input-group">
		                <span class="input-group-addon" style="min-width: 150px;">Compila</span>
		                <select class="form-control" id="edita_activo" name="edita_activo">
					    	<option value="1">Activo</option>
					    	<option value="0">Inactivo</option>
					   </select>
		            </div>	    		
	    		</div>	    			    		
	    	</div>
	    </div>
     </form>
   </div>
 </div>
</div>

   <!-- DataTables JavaScript -->
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables/js/jquery.dataTables.min.js"></script>
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables-plugins/dataTables.bootstrap.min.js"></script>
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables-responsive/dataTables.responsive.js"></script>

   <!-- Page-Level Demo Scripts - Tables - Use for reference -->
   <script>
    $(document).ready(function() {
        $('#dataTable-usuarios').DataTable({
            responsive: true,
            "language":{
    "sProcessing":     "Procesando...",
    "sLengthMenu":     "Mostrar _MENU_ registros",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
        "sFirst":    "Primero",
        "sLast":     "Último",
        "sNext":     "Siguiente",
        "sPrevious": "Anterior"
    },
    "oAria": {
        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
}

        });
    });
   </script>






