<?php
	if(!isset($_GET['exportar'])){
?>
<link rel="stylesheet" type="text/css" href="public/css/daterangepicker.css">
<script type="text/javascript" src="public/js/moment.js"></script>
<script type="text/javascript" src="public/js/daterangepicker.js"></script>
<form class="form-inline" method="get" name="filtroform" id="filtroform">
<?= $this->formFiltroSeguimientoOrdenAdmin->fecha_de ?>         
<?= $this->formFiltroSeguimientoOrdenAdmin->fecha_hasta ?>
	<div class="row">
		<div class="col-md-2">
			<?= $this->formFiltroSeguimientoOrdenAdmin->id_usuario_admin_atiende ?>            		
		</div>
		<div class="col-md-2">
			<?= $this->formFiltroSeguimientoOrdenAdmin->id_motivo ?>                    
		</div>
		<div class="col-md-2">
			<?= $this->formFiltroSeguimientoOrdenAdmin->id_orden_servicio_estatus ?>
		</div>
		<div class="col-md-2">
			<?= $this->formFiltroSeguimientoOrdenAdmin->daterange ?>
		</div>
		<div class="col-md-1">
			<?= $this->formFiltroSeguimientoOrdenAdmin->Filtrar ?>
		</div>
		<div class="col-md-1">
			<?= $this->formFiltroSeguimientoOrdenAdmin->exportar ?>
		</div>
	</div>
</form>
<?php } ?>
<?php if(isset($_GET['exportar'])){ ?>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<table>
	<caption>Ordenes de servicio de la agencia: <?php echo $this->datosAgencia['nombre']?> 	<h3>Se muestra(n): <?php echo $this->totalOrdServ ?> Orden(es)</h3> </caption>
	<thead>
		<tr>
			<th>Id Orden</th>
			<th>Fecha Alta</th>
			<th>Estatus</th>
			<th>Tipo de Soporte</th>
			<th>Motivo</th>
			<th>Ejecutivo</th>
			<th>Producto</th>
			<th>Conformidad</th>
			<th>Descripción de Recepción</th>
			<th>Motivo</th>
			<th>Solución</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ( $this->ordServ as $value) { ?>	
		<tr>
			<td style="vertical-align: top;"><?= $value['id_orden_servicio'] ?></td>
			<td style="vertical-align: top;"><?= $value['fecha_alta'] ?></td>
			<td style="vertical-align: top;"><?= $value['descripcion_estatus'] ?></td>
			<td style="vertical-align: top;"><?= $value['description_tipo_soporte'] ?></td>
			<td style="vertical-align: top;"><?= $value['motivo'] ?></td>
			<td style="vertical-align: top;"><?= $value['nombre_usr_admin_atiende'].' '. $value['ap_usr_admin_atiende'] ?></td>
			<td style="vertical-align: top;"><?= $value['nombre_producto'] ?></td>
			<td style="vertical-align: top;"><?= $value['conformidad'] ?></td>
			<td style="vertical-align: top;"><?= $value['comentarios_recepcion'] ?></td>
			<td style="vertical-align: top;"><?= $value['motivo_orden'] ?></td>
			<td style="vertical-align: top;"><?= $value['solucion_orden'] ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php } else {?>
<table class="table">
	<caption>Ordenes de servicio de la agencia: <?php echo $this->datosAgencia['nombre']?> 	<h3>Se muestra(n): <?php echo $this->totalOrdServ ?> Orden(es)</h3> </caption>
	<thead>
		<tr>
			<th style="min-width: 250px; max-width: 250px;">Datos Generales</th>
			<th>Detalles de la Orden</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ( $this->ordServ as $value) { 
			
			$fecha = new Zend_Date($value["fecha_alta"]);
			$fechaString = $fecha->toString('d MMMM yyyy, H:m:s');
			$value["fecha_alta"]= $fechaString;
			?>	
		<tr>
		
		<td>
			<p>Id Orden: <b><?= $value['id_orden_servicio'] ?></b></p>
			<p>Fecha Alta: <b><?= $value['fecha_alta'] ?></b></p>
			<p>Estatus: <b><?= $value['descripcion_estatus'] ?></b></p>
			<p>Tipo de Soporte: <b><?= $value['description_tipo_soporte'] ?></b></p>
			<p>Motivo: <b><?= $value['motivo'] ?></b></p>
			<p>Ejecutivo: <b><?= $value['nombre_usr_admin_atiende'].' '. $value['ap_usr_admin_atiende'] ?></b></p>
			<p>Producto: <b><?= $value['nombre_producto'] ?></b></p>
			<p>Conformidad: <b><?= $value['conformidad'] ?></b></p>
		</td>
			<td>
				<div class="row" style="padding-bottom: 5px;">
					<div class="col-md-12" style="background-color: #BCF5A9">
						<b>Descripción de Recepción:</b> <?= $value['comentarios_recepcion'] ?>      		
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-6" style="background-color: #CEECF5">
						<b>Motivo:</b> <?= $value['motivo_orden'] ?>  
					</div>
					<div class="col-md-6" style="background-color: #F6E3CE">
						<b>Solución:</b> <?= $value['solucion_orden'] ?>        		
					</div>
				</div>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php } ?>
<?php
	if(isset($_GET['exportar'])){
	header ( "Content-type: application/octet-stream" );
	header ( "Content-Disposition: attachment; filename=reporte_ordenes_de_servicio.xls" );
	header ( "Pragma: no-cache" );
	header ( "Expires: 0" );
	} else {
?>
<script type="text/javascript">
$(function() {
    $('input[name="daterange"]').daterangepicker({ 
    	autoUpdateInput: false,
        locale: {
        format: 'YYYY-MM-DD'},
	    "applyLabel": "Aplicar",
	    "cancelLabel": "Limpiar",
	    "fromLabel": "De",
	    "toLabel": "Hasta",
	    "customRangeLabel": "Custom",
	    "daysOfWeek": [
	        "Do",
	        "Lu",
	        "Ma",
	        "Mi",
	        "Ju",
	        "Vi",
	        "Sa"
	    ],
	    "monthNames": [
	        "Enero",
	        "Febrero",
	        "Marzo",
	        "Abril",
	        "Mayo",
	        "Junio",
	        "Julio",
	        "Agusto",
	        "Septiembre",
	        "Octubre",
	        "Noviembre",
	        "Diciembre"
	    ]
    }, function(start, end, label) {
       // console.log("New date range selected: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
		$("#fecha_de").val(start.format('YYYY-MM-DD'));
		$("#fecha_hasta").val(end.format('YYYY-MM-DD'));
    });

    $('input[name="daterange"]').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
    });

    $('input[name="daterange"]').on('cancel.daterangepicker', function(ev, picker) {
		$("#fecha_de").val('');
		$("#fecha_hasta").val('');
        
        $(this).val('');
    });
});
</script>
<?php } ?>