<h1 class="page-header">Seguimiento Ordenes de Servicio</h1>


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-8 table-responsive">
		<table width="100%" class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th class="amarillo">Lamada sin Contestar</th>
					<th class="naranja">Reportarse</th>
					<th class="rojo">Reportarse Urgente</th>
					<th class="">Otros Servicios</th>
					<th class="morado">Externos</th>
					
				</tr>
			</thead>
			<tbody align="center" id="body-ts">		
			</tbody>		
		</table>
	</div>
</div>


	<form class="form-inline" method="get" name="filtroform" id="filtroform">
	</form>


<div class="alert alert-default alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    Se muestran <?php echo $this->countArray ?> resultados
</div>

<div class="row">
	<div class="col-md-12">


<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
  	<?php foreach ($this->paginator as $registro) { 
  		$color='';
  		switch ($registro["id_orden_servicio_estatus"]){
  			case '1':
  				$color='bs-callout-amarillo';
  			break;
  			case '2':
  				$color='bs-callout-naranja';
  			break;
  			case '3':
  				$color='bs-callout-rojo';
  			break;
  			case '4':
  				$color='bs-callout-gris';
  			break;
  			case '5':
  				$color='bs-callout-morado';
  			break;
  		}
  		?>
		
		<div class="panel panel-default bs-callout2 <?= $color ?>">
		 	<div class="panel-heading <?= $color ?>2">
            	<b>
            	<div class="row">
            		<div class="col-md-9">
            			<center><?= $registro["agencia_nombre"] ?></center>
            		</div>
            		<div class="col-md-3" align="right">
            			ID Orden Servicio: <?= $registro["id_orden_servicio"].'-'.$registro["id_orden_servicio_estatus"]?>
            		</div>
            	</div>
            	</b>
            </div>
		 	<div class="panel-body">
			 	<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label>Fecha Solicitud:</label>
							<p><?= $registro["fecha_alta"] ?></p>
                        </div>
 						<div class="form-group">
                            <label>Fecha Respuesta:</label>
							<p><?= $registro["fecha_cierre"] ?></p>
                        </div>  
 						<div class="form-group">
                            <label>Producto:</label>
							<p></p>
                        </div>                                              
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label>Usuario Solicitante:</label>
							<p><?= $registro["usuario_agencia_nombre"] ?> <?= $registro["usuario_agencia_apellidos"] ?></p>
                        </div>
                        <br/>
 						<div class="form-group">
                            <label>Usuario Atenci&oacute;n:</label>
							<p><?= $registro["clave"] ?></p>
                        </div>    
					</div>
					<div class="col-lg-3 col-md-6">
 						<div class="form-group">
                            <label>Comentarios Recepci&oacute;n:</label>
							<p><?= $registro["comentarios_recepcion"] ?></p>
                        </div>   
                        <div class="form-group">
                            <label>Descripci&oacute;n / Soporte:</label>
				  			<p><?= $registro["descripcion"] ?></p>
                        </div>   
					</div>
					<div class="col-lg-3 col-md-6">
	                    <div class="panel panel-green">
	                        <div class="panel-heading">
	                            <div class="row">
	                                <div class="col-xs-3">
	                                    <i class="fa  fa-play-circle fa-5x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <div class="huge">12</div>
	                                    <div>Empezar</div>
	                                </div>
	                            </div>
	                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Duraci&oacute;n del Servicio:  </span>
                                <span class="pull-left"><?= $registro["duracion_servicio"] ?></span>
                                <span class="pull-right"><i class="fa fa-times-circle-o"></i></span>
                                <div class="clearfix"></div>
                            </div>
	                    </div>
	                </div>
				</div>
	
			  	<hr style=" margin-top: 5px; margin-bottom: 10px;">	  		    
			  	<div class="row">
				  	<div class="col-md-6">
				  		<label>Motivo:</label>
				  		<textarea class="form-control" rows="3" value="<?= $registro["motivo"] ?>"></textarea>
				  	</div>
				  	<div class="col-md-6">
				  		<label>Solución:</label>
				  		<textarea class="form-control" rows="3" value="<?= $registro["solucion"] ?>"></textarea>
				  	</div>				  	
			  	</div>
			  	<br/>
			  	<hr style=" margin-top: 5px; margin-bottom: 10px;">	  		    
			  	<div class="row">
				  	<div class="col-md-4">
				  		<label>Conformidad:</label>
				  		<input class="form-control">
				  	</div>
				  	<div class="col-md-6">
				  		<center><label>Enviar Mail Al Cliente:</label></center>
				  		<div class="row">
				  			<div class="col-md-1"></div>
				  			<div class="col-md-4">
				  				<button type="button" class="btn btn-primary">Servicio en Proceso</button>
				  			</div>
				  			<div class="col-md-2"></div>
				  			<div class="col-md-4">
				  				<button type="button" class="btn btn-primary">Servicio Concluido</button>
				  			</div>
				  			<div class="col-md-1"></div>
				  		</div>
				  	</div>
				  	<div class="col-md-1"></div>	
				  	<div class="col-md-1">
						<button type="button" class="btn btn-primary btn-circle btn-lg"><i class="fa fa-floppy-o  "></i>
                            </button>
				  	</div>				  				  	
			  	</div>			  				    
<!-- 		    	<hr style=" margin-top: 5px; margin-bottom: 10px;">
			  	<div class="row">
				  	<div class="col-md-10">
				  		Control Cron:
				  		<p><?= $registro["control_cron_estatus"] ?></p>
				  	</div>
				  	<div class="col-md-2">
				  		Concluido:
				  		<p><?= $registro["concluido"] ?></p>
				  	</div>				  	
			  	</div>		
		    	<hr style=" margin-top: 5px; margin-bottom: 10px;"> -->
		  </div>
		</div>
	
	<?php } ?>
	
	</div>
</div>


