<script type="text/javascript">
	window.addEventListener("beforeunload", function (e) {
	    var confirmationMessage = 'It looks like you have been editing something. '
	                            + 'If you leave before saving, your changes will be lost.';

	    (e || window.event).returnValue = confirmationMessage; //Gecko + IE
	    return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
	});
</script>
<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">
<link rel="stylesheet" type="text/css" href="public/css/orden-seguimiento/index.css">

<div class="row">
	<table width="100%" class="table">
		<thead>
			<tr>
				<th class="amarillo centrado">En operación</th>
				<th class="naranja centrado">Reportarse</th>
				<th class="rojo centrado">Reportarse Urgente</th>
				<th class="centrado">Otros Servicios</th>
				<th class="morado centrado">Externos</th>		
			</tr>
		</thead>	
	</table>
</div>
<form class="form-inline" method="get" name="filtroform" id="filtroform">
</form>
	<h3 style="margin-top: 0px;margin-bottom: 0px;">Se muestra(n) <b id="total_ordenes"></b> resultado(s):</h3>
<div class="row">
	<div class="col-md-12">
	<div class="row" align="right">
		<?=$this->paginationControl ($this->paginator, 'Sliding');?>
	</div>
	<?php $id_orden_servicio_todos=","?>
	<?php $duracion_servicio_todos=","?>
	<?php $control_cron_estatus_todos=","?>
	<?php $motivo_todos=","?>

	<?php foreach ($this->paginator as $registro) { ?>
  	<form id="formOrSr_<?= $registro['id_orden_servicio'] ?>">

  	<?php  
  		$color='';

		if($registro['control_cron_estatus']!=0){
	  		switch ($registro["id_orden_servicio_estatus"]){
	  			case '1':
	  				$color='bs-callout-amarillo-verde';
	  			break;
	  			case '2':
	  				$color='bs-callout-naranja-verde';
	  			break;
	  			case '3':
	  				$color='bs-callout-rojo-verde';
	  			break;
	  			case '4':
	  				$color='bs-callout-gris-verde';
	  			break;
	  			case '5':
	  				$color='bs-callout-morado-verde';
	  			break;
	  		}
		}else{
	  		switch ($registro["id_orden_servicio_estatus"]){
	  			case '1':
	  				$color='bs-callout-amarillo';
	  			break;
	  			case '2':
	  				$color='bs-callout-naranja';
	  			break;
	  			case '3':
	  				$color='bs-callout-rojo';
	  			break;
	  			case '4':
	  				$color='bs-callout-gris';
	  			break;
	  			case '5':
	  				$color='bs-callout-morado';
	  			break;
	  		}		
		}
  		//if($registro["control_cron_estatus"]!=3){
  			
			// Llena las opciones del formulario de acuerdo a la agencia que corresponda la orden de servicio.  		
	  		$poliza = new Application_Model_DbTable_Poliza();
	  		$polizasAgencia = $poliza->obtenerPolizasVigentesPorIdAgencia($registro['id_agencia']);
	  		$options = array();
	  		foreach ($polizasAgencia as $key => $value){
	  			$options[$value['id_poliza']] = $value['clave'];
	  		}
	  		$this->formSeguimientoOrden->id_poliza->addMultiOptions($options);
	  		
	    	$producto = new Application_Model_DbTable_Producto();
	        $productos = $producto->obtenerProductosRegistradosPorAgencia($registro['id_agencia']);
	  		$options = array();
	  		foreach ($productos as $key => $value){
	  			$options[$value['id_producto']] = $value['nombre_prod'];
	  		}
	  		$this->formSeguimientoOrden->id_producto->addMultiOptions($options);  		

	  		$utiles = new Application_Model_Services_Utiles();
	  		$params = array(
	  			'id_usuario_soporte_titular' => $registro['id_usuario_soporte_titular'],
				'id_usuario_soporte_auxiliar' => $registro['id_usuario_soporte_auxiliar']
	  		);
	  		
	  		$ejecutivos = $utiles->consultarejecutivosporidService($params);
	  		$options = array();
	  		foreach ($ejecutivos as $key => $value){
	  			$options[$key] = $value;
	  		}
	  		$this->formSeguimientoOrden->id_usuario_admin_atiende->addMultiOptions($options);

			$options = array('' => 'Otro');
			$usuario_agencia = new Application_Model_DbTable_AgenciaUsuario();
			$usuariosAgencia = $usuario_agencia->obtenerUsuariosDeAgenciaPorIdAgencia($registro['id_agencia']);

	  		foreach ($usuariosAgencia as $key => $value){
	  			$options[$value['id_usuario_agencia']] = $value['nombre']." ".$value['apellidos'];
  			}
	  		
	  		$this->formSeguimientoOrden->id_usuario_agencia_solicito->addMultiOptions($options);
	  		
	  		$this->formSeguimientoOrden->populate($registro);

	  		//echo "<pre>".print_r($registro,true)."</pre>";
	  		 
	  		$fecha = new Zend_Date($registro["fecha_alta"]);
	  		$fechaString = $fecha->toString('d MMMM yyyy, H:m:s');
	  		$registro["fecha_alta"]= $fechaString;
	  		
  		?>
		<?= $this->formSeguimientoOrden->id_orden_servicio ?>
		<div id="orden_servicio_<?= $registro["id_orden_servicio"]?>" class="panel panel-default bs-callout2 <?= $color ?>">
		 	<div class="panel-heading <?= $color ?>2">
            	<b>
            	<div class="row">
            		<div class="col-md-9">
            			<span  id='consulta-ordenes' class="btn btn-default" onClick="vinculo(<?= $registro['id_agencia'] ?>)">
            			<?= $registro["nombre"] ?>
            			</span>
           				<a  class="btn btn-info" href="<?= $this->baseUrl() ?>/agencias/index/id_agencia/<?= $registro['id_agencia'] ?>" target="_blank"> Detalles</a>
            		</div>
            		<div class="col-md-3" align="right">
            			ID Orden Servicio: <?= $registro["id_orden_servicio"] ?>
            		</div>
            	</div>
            	</b>
            </div>
		 	<div class="panel-body">
			 	<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label >Fecha Solicitud:</label>
							<p><?= $registro["fecha_alta"] ?></p>
                        </div>
                        <div class="form-group">
                            <label>Descripci&oacute;n / Soporte:</label>
				  			<p><?= $registro["descripcion_estatus"] ?></p>
                        </div> 
                        <div class="form-group">
                            <label>Comentario Recepci&oacute;n:</label>
				  			<p><?= $registro["comentarios_recepcion"] ?></p>
                        </div>
 						<div class="form-group">
							<?= $this->formSeguimientoOrden->id_producto ?>
                        </div>   
                         <div class="form-group">
							<?= $this->formSeguimientoOrden->id_poliza ?>
                        </div>
					</div>
					<div class="col-lg-3 col-md-6">
					    <div class="form-group">
							<?= $this->formSeguimientoOrden->id_usuario_admin_atiende ?>
                        </div>  
						<div class="form-group">
							<?= $this->formSeguimientoOrden->id_motivo ?>
                        </div>
						<div class="form-group">
							<?= $this->formSeguimientoOrden->id_usuario_agencia_solicito ?>
                        </div>
						<div class="form-group">
							<?= $this->formSeguimientoOrden->solicito_otro ?>
                        </div>

					</div>
					<div class="col-lg-3 col-md-6">
                        <div class="form-group">
							<?= $this->formSeguimientoOrden->motivo_orden ?>
                        </div>
                        <div class="form-group">
							<?= $this->formSeguimientoOrden->solucion_orden ?>
                        </div>
                        
                        
					</div>
					<div class="col-lg-3 col-md-6">
	                    <!-- AQUI ES EL CRONOMETRO -->


	                    <div class="panel <?= $color ?>2" >
	                        <div class="panel-heading">
	                            <div class="row">
	                                <div value="pause" id="mainBtn_<?= $registro["id_orden_servicio"]?>" onclick="clickPausePlayBtn(<?= $registro["id_orden_servicio"]?>)" class="col-xs-3">
	                                    <i id="playPauseBtn_<?= $registro["id_orden_servicio"]?>" class="fa  fa-play-circle fa-5x botton-play_green"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                	<div style="font-size:25px;"id="cron_<?= $registro["id_orden_servicio"]?>"></div>
	                                  	<svg class="recSVG" id="recSVG_<?= $registro["id_orden_servicio"]?>" width="20" height="20">
										   <circle cx="10" cy="10" r="8"  stroke-width="1" fill="red" />
										</svg>
	                                </div>
	                            </div>
	                        </div>
<!--                             <div class="panel-footer">
                                <span class="pull-left">Duraci&oacute;n del Servicio:  </span>
                                <span class="pull-left"><?= $registro["duracion_servicio"] ?></span>
                                <span class="pull-right"><i class="fa fa-times-circle-o"></i></span>
                                <div class="clearfix"></div>
                            </div> -->
	                    </div>
	                </div>
	                
				</div>
			  	<hr style=" margin-top: 5px; margin-bottom: 10px;">	  		    
			  	<div class="row">
				  	<div class="col-md-6 form-group">
                        <div class="form-group">
							<?= $this->formSeguimientoOrden->conformidad ?>
                        </div>
				  	</div>
		  			<div class="col-md-2 form-group" align="center">
		  			<br>

		  			<button name="accion_os" onclick="guardarServicioAjax(<?= $registro["id_orden_servicio"]?>,1)" class="btn btn-primary prevent-default"/>Guardar Cambios</button>
		  			</div>					  			
				  	<div class="col-md-2" align="center">
				  	<br>
			  			<input name="accion_os" id="concluirServicio_<?= $registro["id_orden_servicio"] ?>"  onclick="guardarServicioAjax(<?= $registro["id_orden_servicio"]?>,6)" type="button" class="btn btn-primary prevent-default" value="Cerrar Servicio" />
				  	</div>			  				  	
			  	</div>	
		  </div>
		</div>

		<?php $id_orden_servicio_todos = $id_orden_servicio_todos . $registro["id_orden_servicio"] . ","  ?>
		<?php $duracion_servicio_todos = $duracion_servicio_todos . $registro["duracion_servicio_segundos"] . ","  ?>
		<?php $control_cron_estatus_todos = $control_cron_estatus_todos . $registro["control_cron_estatus"] . ","  ?>
		<?php $motivo_todos = $motivo_todos . $registro["motivo"] . ","  ?>
	</form>
	<?php 
	//	}
	} ?>
	<span id="info_id_ordenes" hidden="true"> <?= $id_orden_servicio_todos ?> </span>
	<span id="info_duracion_servicio_todos" hidden="true"> <?= $duracion_servicio_todos ?> </span>
	<span id="info_control_cron_estatus_todos" hidden="true"> <?= $control_cron_estatus_todos ?> </span>
	<span id="info_motivo_todos" hidden="true"> <?= $motivo_todos ?> </span>
	</div>
	
	<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
</div>


