<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">

<h1 class="page-header">Seguimiento Ordenes de Servicio</h1>


<div class="row">
	<table width="100%" class="table">
		<thead>
			<tr>
				<th class="amarillo">Lamada sin Contestar</th>
				<th class="naranja">Reportarse</th>
				<th class="rojo">Reportarse Urgente</th>
				<th class="">Otros Servicios</th>
				<th class="morado">Externos</th>		
			</tr>
		</thead>	
	</table>
</div>
<form class="form-inline" method="get" name="filtroform" id="filtroform">
<form>


<h2>Se muestra(n) <b id="total_ordenes"></b> resultado(s):</h2>

<div class="row">
	<div class="col-md-12">


<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
	<?php $id_orden_servicio_todos=","?>
	<?php $duracion_servicio_todos=","?>
	<?php $control_cron_estatus_todos=","?>
	<?php $motivo_todos=","?>
  	<?php foreach ($this->paginator as $registro) { 
  		$color='';

		if($registro['control_cron_estatus']!=0){
  		switch ($registro["id_orden_servicio_estatus"]){
  			case '1':
  				$color='bs-callout-amarillo-verde';
  			break;
  			case '2':
  				$color='bs-callout-naranja-verde';
  			break;
  			case '3':
  				$color='bs-callout-rojo-verde';
  			break;
  			case '4':
  				$color='bs-callout-gris-verde';
  			break;
  			case '5':
  				$color='bs-callout-morado-verde';
  			break;
  		}
		}else{
  		switch ($registro["id_orden_servicio_estatus"]){
  			case '1':
  				$color='bs-callout-amarillo';
  			break;
  			case '2':
  				$color='bs-callout-naranja';
  			break;
  			case '3':
  				$color='bs-callout-rojo';
  			break;
  			case '4':
  				$color='bs-callout-gris';
  			break;
  			case '5':
  				$color='bs-callout-morado';
  			break;
  		}		
		}


  		if($registro["control_cron_estatus"]!=3){
  		?>
	
		<div id="orden_servicio_<?= $registro["id_orden_servicio"]?>" class="panel panel-default bs-callout2 <?= $color ?>">
		 	<div class="panel-heading <?= $color ?>2">
            	<b>
            	<div class="row">
            		<div class="col-md-9">
            			<center><?= $registro["agencia_nombre"] ?></center>
            		</div>
            		<div class="col-md-3" align="right">
            			ID Orden Servicio: <?= $registro["id_orden_servicio"].'-'.$registro["id_orden_servicio_estatus"]?>
            		</div>
            	</div>
            	</b>
            </div>
		 	<div class="panel-body">
			 	<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label >Fecha Solicitud:</label>
							<p><?= $registro["fecha_alta"] ?></p>
                        </div>
 						<div class="form-group">
                            <label>Fecha Respuesta:</label>
							<p><?= $registro["fecha_cierre"] ?></p>
                        </div>  
 						<div class="form-group">
                            <label>Producto:</label>
							<p></p>
                        </div>                                              
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label>Usuario Solicitante:</label>
							<p><?= $registro["usuario_agencia_nombre"] ?> <?= $registro["usuario_agencia_apellidos"] ?></p>
                        </div>
                        <br/>
 						<div class="form-group">
                            <label>Usuario Atenci&oacute;n:</label>
							<p><?= $registro["clave"] ?></p>
                        </div>    
					</div>
					<div class="col-lg-3 col-md-6">
 						<div class="form-group">
                            <label>Comentarios Recepci&oacute;n:</label>
							<p><?= $registro["comentarios_recepcion"] ?></p>
                        </div>   
                        <div class="form-group">
                            <label>Descripci&oacute;n / Soporte:</label>
				  			<p><?= $registro["descripcion"] ?></p>
                        </div>   
					</div>
					<div class="col-lg-3 col-md-6">
	                    <!-- AQUI ES EL CRONOMETRO -->


	                    <div class="panel <?= $color ?>2" >
	                        <div class="panel-heading">
	                            <div class="row">
	                                <div value="pause" id="mainBtn_<?= $registro["id_orden_servicio"]?>" onclick="clickPausePlayBtn(this.id)" class="col-xs-3">
	                                    <i id="playPauseBtn_<?= $registro["id_orden_servicio"]?>" class="fa  fa-play-circle fa-5x"></i>
	                                   <!--  <div>Comenzar</div> -->

	                                </div>
	                                <div class="col-xs-9 text-right">

	                                <div style="font-size:25px;"id="cron_<?= $registro["id_orden_servicio"]?>"></div>
	                                  	<svg class="recSVG" id="recSVG_<?= $registro["id_orden_servicio"]?>" width="20" height="20">
										   <circle cx="10" cy="10" r="8"  stroke-width="1" fill="red" />
										</svg>
	                                    
	                                    
	                                </div>
	                            </div>
	                        </div>
<!--                             <div class="panel-footer">
                                <span class="pull-left">Duraci&oacute;n del Servicio:  </span>
                                <span class="pull-left"><?= $registro["duracion_servicio"] ?></span>
                                <span class="pull-right"><i class="fa fa-times-circle-o"></i></span>
                                <div class="clearfix"></div>
                            </div> -->
	                    </div>
	                    <div align="right">
	                    <a class="btn <?= $color ?>2" href="#orden_<?= $registro["id_orden_servicio"]?>" data-toggle="collapse"><i class="fa fa-chevron-down"></i></a></div>
	                </div>
				</div>
			  	  

				<hr style=" margin-top: 5px; margin-bottom: 10px;">	
				<div id="orden_<?= $registro["id_orden_servicio"]?>" class="collapse">
				  	<div class="row">
					  	<div class="col-md-6 form-group">
					  		<label>Motivo:</label>
					  		<textarea id="motivo_<?= $registro["id_orden_servicio"]?>" class="form-control" rows="3" value="<?= $registro["motivo"] ?>"><?= $registro["motivo"] ?></textarea>
					  	</div>
					  	<div class="col-md-6 form-group">
					  		<label>Solución:</label>
					  		<textarea id="solucion_<?= $registro["id_orden_servicio"]?>" class="form-control" rows="3" value="<?= $registro["solucion"] ?>"><?= $registro["solucion"] ?></textarea>
					  	</div>				  	
				  	</div>
				  	<br/>
				  	<hr style=" margin-top: 5px; margin-bottom: 10px;">	  		    
				  	<div class="row">
					  	<div class="col-md-4 form-group">
					  		<label>Conformidad:</label>
					  		<input id="conformidad_<?= $registro["id_orden_servicio"]?>" class="form-control">
					  	</div>
					  	<div class="col-md-6">
					  		<div class="row">
					  			<div class="col-md-3">
					  			</div>
					  			<div class="col-md-2">
					  				<button id="concluirServicio_<?= $registro["id_orden_servicio"] ?>" onclick="concluirSercicioAjax(this.id)" type="button" class="btn btn-primary">Servicio Concluido</button>
					  			</div>
								<div class="col-md-2"></div>
					  			<div class="col-md-2">
					  				<button id="guardarServicio_<?= $registro["id_orden_servicio"] ?>" onclick="guardarSercicioAjax(this.id)" type="button" class="btn btn-primary">Guardar Servicio</button>
					  			</div>					  			
					  			<div class="col-md-3"></div>
					  		</div>
					  	</div>
					  	<div class="col-md-2"></div>			  				  	
				  	</div>	
				</div>
		  </div>
		</div>

		<?php $id_orden_servicio_todos = $id_orden_servicio_todos . $registro["id_orden_servicio"] . ","  ?>
		<?php $duracion_servicio_todos = $duracion_servicio_todos . $registro["duracion_servicio"] . ","  ?>
		<?php $control_cron_estatus_todos = $control_cron_estatus_todos . $registro["control_cron_estatus"] . ","  ?>
		<?php $motivo_todos = $motivo_todos . $registro["motivo"] . ","  ?>
	
	<?php 
		}
	} ?>
	<p id="info_id_ordenes" hidden="true"> <?= $id_orden_servicio_todos ?> </p>
	<p id="info_duracion_servicio_todos" hidden="true"> <?= $duracion_servicio_todos ?> </p>
	<p id="info_control_cron_estatus_todos" hidden="true"> <?= $control_cron_estatus_todos ?> </p>
	<p id="info_motivo_todos" hidden="true"> <?= $motivo_todos ?> </p>
	</div>
	
	<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
</div>


