	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           	<div class="panel-heading ">
	                <h4 class="page-header">Reporte Avanzado de Agencias</h4>
	           	</div>
	           	<div class="panel-body">
	           		<form id="form-busqueda-agencia"  class="form-busqueda-agencia" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
			           	<div class="row">
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Nombre Agencia</i>
					                </span>
					               	<?= $this->form->nombre ?>
				            	</div>
								
							</div>
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Nombre Comercial</i>
					                </span>
					               	<?= $this->form->nombre_comercial ?>
				            	</div>
							</div>
							<div class="col-md-2">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> RFC</i>
					                </span>
					               	<?= $this->form->rfc ?>
				            	</div>
							</div>
							<div class="col-md-2">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Estatus</i>
					                </span>
					               	<?= $this->form->estatus ?>
				            	</div>
							</div>
						</div>
			           	<div class="row">
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Ciudad</i>
					                </span>
					               	<?= $this->form->ciudad ?>
				            	</div>
							</div>
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Estado</i>
					                </span>
					               	<?= $this->form->estado ?>
				            	</div>
							</div>
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> C&oacute;digo Postal</i>
					                </span>
					               	<?= $this->form->cp ?>
				            	</div>							
							</div>
						</div>					
			           	<div class="row">
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Contacto</i>
					                </span>
					               	<?= $this->form->contacto ?>
				            	</div>
							</div>
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Email</i>
					                </span>
					               	<?= $this->form->email ?>
				            	</div>
							</div>
							<div class="col-md-4">
								<div class="form-group input-group">
					                <span class="input-group-addon"><i class="fa fa-info-circle"> Ejecutivo</i>
					                </span>
					               	<?= $this->form->ejecutivo ?>
				            	</div>
							</div>
						</div>	
				    	<div class="row">
							<div class="col-md-3">
								
							</div>			    	
				    		<div class="col-md-6">
				    			<?= $this->form->licencias ?>
				    		</div>
							<div class="col-md-3">
								
							</div>			    		
				    	</div>	
				    	<div class="row">
							<div class="col-md-3">
								
							</div>			    	
				    		<div class="col-md-6">
				    			
				    		</div>
							<div class="col-md-3">
								<button type="button" class="btn btn-success btn-circle btn-lg" id="action-form-agencia" onclick="submitFormBusquedaAgencia()"><i class="fa fa-save"></i></button>
							</div>			    		
				    	</div>
			    	</form>															
					<br/>
<!-- 					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre</th>
								<th>Estatus</th>
								<th>Correo</th>
								<th>Detalles</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->registros as $registro) { ?>
							<tr id='<?php echo $registro['id_usuario'] ?>'
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_usuario'] ?></td>
								<td><?php echo $registro['clave'] ?></td>
								<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 'S' ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td><?php echo $registro['email'] ?></td>
								<td >
									<button type="button" class="btn btn-primary btn-sm btn-circle" data-toggle="modal" data-target="#myModal" value='<?= json_encode($registro) ?>'
									onclick="datosform_edita_usuario(this.value)">
									<i class="fa fa-info-circle"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table> -->
				</div>
			</div>
		</div>
	</div>
	<br/>

  <script type="text/javascript">
  	$('#licencias').multiSelect();
  </script>
