	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           <div class="panel-heading ">
	                <h4 class="page-header">Reporte Avanzado de Agencias</h4>
	           </div>
	           <div class="panel-body">
		           	<div class="row">
						<div class="col-md-4">
							Nombre Agencia
						</div>
						<div class="col-md-4">
							Nombre Comercial
						</div>
						<div class="col-md-2">
							RFC
						</div>
						<div class="col-md-2">
							Estatus
						</div>
					</div>
		           	<div class="row">
						<div class="col-md-4">
							Ciudad
						</div>
						<div class="col-md-4">
							Estado
						</div>
						<div class="col-md-4">
							C&oacute;digo Postal
						</div>
					</div>					
		           	<div class="row">
						<div class="col-md-4">
							Contacto
						</div>
						<div class="col-md-4">
							Email
						</div>
						<div class="col-md-4">
							Ejecutivo
						</div>
					</div>	
					<div class="row">
						<div class="col-md-3">
							Garantia
						</div>
						<div class="col-md-3">
							Poliza
						</div>
						<div class="col-md-3">
							Factura Electronica
						</div>
						<div class="col-md-3">
							Timbrado
						</div>
					</div>
					Productos
					<div class="row">
						<div class="col-md-2">
							ICAAVWin
						</div>
						<div class="col-md-2">
							IRISWin
						</div>
						<div class="col-md-2">
							Centauro
						</div>
						<div class="col-md-2">
							GVC
						</div>
						<div class="col-md-2">
							Boleto - E
						</div>
					</div>
					Interfaces
					<div class="row">
						<div class="col-md-3">
							Amadeus
						</div>
						<div class="col-md-3">
							Apollo
						</div>
						<div class="col-md-3">
							Sabre
						</div>
						<div class="col-md-3">
							Worldspan
						</div>
					</div>										
					<br/>
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre</th>
								<th>Estatus</th>
								<th>Correo</th>
								<th>Detalles</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->registros as $registro) { ?>
							<tr id='<?php echo $registro['id_usuario'] ?>'
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_usuario'] ?></td>
								<td><?php echo $registro['clave'] ?></td>
								<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 'S' ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td><?php echo $registro['email'] ?></td>
								<td >
									<button type="button" class="btn btn-primary btn-sm btn-circle" data-toggle="modal" data-target="#myModal" value='<?= json_encode($registro) ?>'
									onclick="datosform_edita_usuario(this.value)">
									<i class="fa fa-info-circle"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<br/>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">

     <div class="modal-header">
     	<div class="row">
    		<div class="col-md-10">
				<h4 class="modal-title" id="myModalLabel"></h4>
    		</div>
    		<div class="col-md-2" align="right">
       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
    		</div> 			    		
    	</div>
       

     </div>

     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">

	    <div class="modal-body">
			<fieldset>
				<legend>Datos Generales:</legend>
				<div class="row">
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->clave ?>
			            </div>
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->nombre ?>
			            </div>
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->apellido_paterno ?>
			            </div>	    		
		    		</div>
		    		<div class="col-md-4">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-user"></i>
			                </span>
			                <?= $this->form->apellido_materno ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span>
			                <?= $this->form->pwd ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-lock"></i>
			                </span>
			                <?= $this->form->pwd_conf ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-suitcase"></i>
			                </span>
			                <?= $this->form->puesto ?>
			            </div>
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon"><i class="fa fa-envelope"></i>
			                </span>
			                <?= $this->form->email ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon">Estatus</span>
			                <?= $this->form->activo ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
			</fieldset>
			<fieldset>
				<legend>Permisos:</legend>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Admin</span>
			                <?= $this->form->admin ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Supervisor</span>
			                <?= $this->form->supervisor ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Folios</span>
			                <?= $this->form->folios ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Ejecutivo</span>
			                <?= $this->form->compila ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
		    	<div class="row">
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Recepcionista</span>
			                <?= $this->form->folios ?>
			            </div>	   
		    		</div>
		    		<div class="col-md-6">
						<div class="form-group input-group">
			                <span class="input-group-addon" >Ventas ??</span>
			                <?= $this->form->compila ?>
			            </div>	    		
		    		</div>	    			    		
		    	</div>
	    	</fieldset>
	    </div>
	    <div class="modal-footer">     
	       <span id="submitBtn" type="button" class="btn btn-success btn-circle btn-lg" onclick="submitForm()"><i class="fa fa-save"></i></span>
<!-- 	       <button type="button" class="btn btn-danger btn-circle btn-lg" ><i class="fa fa-trash-o"></i></button> -->
	    </div>
     </form>
   </div>
 </div>
</div>