<h1 class="page-header">Administraci&oacute;n de Agencias.</h1>
<div class="row">
	<div class="col-md-10">
		<?= $this->selectAgencias->select_agencias?>
	</div>
	<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_admin']=='S') {?>
	<div class="col-md-2" align="right">
		<button type="button" class="btn btn-success"
			data-dismiss="modal" onclick="abrirModalAgregarAgencia()"
			data-toggle="modal" data-target="#myModal">
			&nbsp;<i class="fa fa-plus"></i>&nbsp;Agencia&nbsp;
		</button>
	</div>
	<?php } ?>
</div>
<div class="salto"></div>
<div id="datos-agencia">
		<?= $this->render('agencias/render/datosAgencia.phtml') ?>
</div>
<div class="row hidden" id="datosAgencia">
	<div class="col-lg-12">
		<div class="panel panel-primary">
			<div class="panel-heading">Nombre de la Agencia</div>
			<div class="panel-footer">Observaciones:</div>
		</div>
	</div>
</div>
<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_admin']=='S') {?>
	<?= $this->render('agencias/render/modalAgregarAgencia.phtml') ?>
<?php } ?>
<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_ejecutivo']=='S') {?>
	<?= $this->render('agencias/render/modalNuevoUsuario.phtml') ?>
<?php } ?>
<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_edita_poliza']=='S') {?>
	<?= $this->render('agencias/render/modalPoliza.phtml') ?>
<?php } ?>
<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_agrega_folios']=='S') {?>
	<?= $this->render('agencias/render/modalNuevosFolios.phtml') ?>
<?php } ?>
<?php if ($_SESSION['Zend_Auth']['USER_VALUES']['p_ventas']=='S') {?>
	<?= $this->render('agencias/render/modalNuevoProducto.phtml') ?>
<?php } ?>
<script type="text/javascript">
	function buscar(){
		document.getElementById('datosAgencia').style.display = 'block';
	}
</script>

<?php 
foreach ( $this->tipoPoliza as $value ){
	?>
	<input id='tipo_poliza_<?= $value['tipo'] ?>' type="hidden" value="<?= $value['horas_soporte_anual'] ?>">
	<?php 
}
?>