<div class="panel panel-primary">
	<div class="panel-heading">
	<b>Nombre de la Agencia</b>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
		        <h4>Direcci&oacute;n</h4>
		        <address>
		            795 Folsom Ave, Suite 600
		            <br>San Francisco, CA 94107
		        </address>
			</div>
			<div class="col-md-4">
		        <h4>Contacto</h4>
		        <address>
		            <abbr title="Phone">P:</abbr>(123) 456-7890
		            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
		            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
		        </address>
			</div>
			<div class="col-md-4">
				<h4>Correos</h4>
				<address>
				    <a href="mailto:#" style="color: #007eae;">first.last@example.com</a>
				</address>
			</div>
		</div>  
		<div class="row">
			<div class="col-md-12 table-responsive">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
					<thead>
						<tr>
							<th>Clave</th>
							<th>Horas</th>
							<th>H.ICAAV</th>
							<th>H. Iris</th>
							<th>Cantidad</th>
							<th>F. Inicial</th>
							<th>F. Final</th>
							<th>Agotado</th>
							<th>Garantia</th>
						</tr>
					</thead>
					<tbody align="center">
						<tr>
							<td>JOMKMR</td>
							<td>30</td>
							<td>30</td>
							<td>0</td>
							<td>0</td>
							<td>18/02/2016</td>
							<td>17/02/2020</td>
							<td>N</td>
							<td>N</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="panel-footer">
    	<p>Observaciones:<object align="right"><b>Tiempo Restante: ??:??</b></object></p><br/>
    	
    </div>	
</div>