<?php if ($this->chart == 1){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart1.php" width="1250" height="750"  marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 2){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart2.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 3){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart3.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 4){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart4.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 5){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart5.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 6){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart6.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 7){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart7.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 8){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/chart8.php" width="1250" height="750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>
<?php if ($this->chart == 9){ ?>
<iframe src="http://derechoalaidentidad.org/form_befoundation/charts.php" width="1250" height="2750" marginheight="0" marginwidth="0" noresize scrolling="No" frameborder="0"></iframe> 
<?php } ?>