 <table class="table">
    <thead>
      <tr>
      <?php  foreach ( $this->agendaArray as $key => $value ) { ?>
        <th width="15%"><?php
        $fecha = new Zend_Date($key);
        $fechaString = $fecha->toString('d MMMM yyyy');
        echo $fechaString;
        ?></th>
       <?php } ?>
      </tr>
    </thead>
<tbody>
      <tr>
<?php  foreach ( $this->agendaArray as $key => $value ) { ?>
        <td>
        	<?php foreach($value as $val) { ?>
        		<b>Ejecutivo:</b> <?= $val['nombre'] ?> <?= $val['apellido_paterno'] ?> <br>
        		<b>Agencia:</b> <?= $val['nombre_agencia'] ?><br>
        		<b>Hora Inicial:</b> <?= $val['hora_inicial'] ?><br>
        		<b>Hora Final:</b> <?= $val['hora_final'] ?><br>
        		<hr>
        	<?php } ?>
        </td>
<?php } ?>
      </tr>
</tbody>
</table>