<a class="btn btn-default" href="<?= $this->baseUrl() ?>/agencia-admin/historico-actualizaciones" role="button">Historico de Actualizaciones</a>
<div class="panel panel-default">
  <div class="panel-body">

  	<?php if ( isset($this->params['status']) ) { ?>
	<div class="alert alert-success" role="alert">Se a ralizado la solicitud exitosamente.</div>
	<?php } ?>
  
<table class="table table-condensed" id="polizas">
<caption>Pólizas.</caption>
<thead>
	<tr>
		<th>Id. Poliza</th>
		<th>Clave</th>
		<th>Producto</th>
		<th>Horas Incluidas</th>
		<th>Horas Consumidas</th>
		<th>Horas Restantes</th>
		<th>Fecha Inicio</th>
		<th>Fecha Cierre</th>
		<th>Estatus</th>
		<th>Nueva Orden</th>

	</tr>
</thead>
<tbody>
<?php foreach ($this->polizasAgencia as $value) { ?>
	<tr>
		<td scope="row"><?= $value['id_poliza'] ?></td>
		<td><a href="public/agencia-admin/consultar-ordenes/id_poliza/<?= $value['id_poliza'] ?>"><?= $value['clave_poliza'] ?></a></td>
		<td><?= $value['nombre_producto'] ?></td>
		<td><?= $value['horas_poliza'] ?></td>
		<td><?= $value['horas_consumidas'] ?></td>
		<td><?= $value['horas_restantes'] ?></td>
		<td><?= $value['fecha_ini'] ?></td>
		<td><?= $value['fecha_fin'] ?></td>
		<td>
				<?php 
			$label = '';
			
			switch ($value['id_poliza_estatus']){
				case 1:
					$label = 'label-success';
					break;
				case 2:
					$label = 'label-warning';
					break;
				case 4:
					$label = 'label-danger';
					break;
				case 3:
					$label = 'label-info';
					break;
				case 5:
					$label = 'label-primary';
					break;
				case 6:
					$label = 'label-default';
					break;
			}
		?>
			<span class="label <?= $label ?>">
			<?= $value['descripcion_estatus'] ?>
			</span>
		</td>
		<td align="center">
		<?php if( $value['id_poliza_estatus']=='1' ) { ?>
		<button type="button" class="btn btn-success" onclick="openFormOrden(<?= $value['id_poliza'] ?>)">
			Click <i class="fa fa-plus-square" aria-hidden="true"></i>
		</button>
		<?php } ?>
		</td>
	</tr>
<?php } ?>
</tbody>
</table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="myModalAddOdSr" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form id="nueva-orden" action="public/agencia-admin/agregar-orden" method="post">
    	<input type="hidden" id="id_poliza" name="id_poliza">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Solicitud de Soporte.</h4>
	      </div>
	      <div class="modal-body">
		<?php echo $this->selectEjecutivo->id_usuario_admin_atiende; ?>	
		<?php echo $this->selectEjecutivo->id_producto; ?>
		<?php echo $this->selectEjecutivo->telefono; ?>
		<?php echo $this->selectEjecutivo->comentarios_recepcion; ?>
		
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        <button type="submit" class="btn btn-primary">Solicitar</button>
	      </div>
	    </div>
    </form>
  </div>
</div>


<script>
function openFormOrden(id_poliza){
	$("#id_poliza").val(id_poliza);
	$('#myModalAddOdSr').modal('show');
}

$(document).ready(function() {
    $('#polizas').DataTable({
        //responsive: true,
        "language":{
			"sProcessing":     "Procesando...",
			"sLengthMenu":     "Mostrar _MENU_ registros",
			"sZeroRecords":    "No se encontraron resultados",
			"sEmptyTable":     "Ning&uacute;n dato disponible en esta tabla",
			"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
			"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
			"sInfoPostFix":    "",
			"sSearch":         "Buscar:",
			"sUrl":            "",
			"sInfoThousands":  ",",
			"sLoadingRecords": "Cargando...",
			"oPaginate": {
			    "sFirst":    "Primero",
			    "sLast":     "&Uacute;timo",
			    "sNext":     "Siguiente",
			    "sPrevious": "Anterior"
			},
			"oAria": {
			    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
			    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
			}
		}
    });
    
} );


</script>