<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<base href="<?= $this->baseUrl() ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="MIG AdminSystem">
    <meta name="author" content="HopeWare">

	<!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css_complete/bootstrap/css/bootstrap.min.css">
    <!-- MetisMenu CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css_complete/metisMenu/metisMenu.min.css" >
    <!-- DataTables CSS -->
    <link href="<?= $this->baseUrl() ?>/css_complete/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="<?= $this->baseUrl() ?>/css_complete/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
 	<!-- Custom CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css_complete/dist/css/sb-admin-2.css">
    <!-- Custom Fonts -->
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css_complete/font-awesome/css/font-awesome.min.css" >

	<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css_complete/bootstrap-select/css/bootstrap-select.min.css">
	<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/panel.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

	<script src="<?= $this->baseUrl() ?>/css_complete/jquery/jquery.min.js"></script>
	<script src="<?= $this->baseUrl() ?>/css_complete/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?= $this->baseUrl() ?>/css_complete/metisMenu/metisMenu.min.js"></script>
    <script src="<?= $this->baseUrl() ?>/js/sb-admin-2.js"></script>
    <script src="<?= $this->baseUrl() ?>/css_complete/bootstrap-select/js/bootstrap-select.min.js"></script> 

	<?php echo $this->InlineScript();  ?>
 	<?php echo $this->headLink(); ?>
</head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>