<br />
<div class="salto"></div>
<div id="alertas">
	
</div>
<div class="panel panel-default">
	<div class="panel-body" id="datos-agencia">
		<div class="panel panel-primary">
			<div class="panel-heading">
			<center>
				<b>
					<span style="color: rgb(255, 255, 255);" class="text-primary" id="nombre_agencia-info"></span>
				</b>
			</center>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-4">
				        <center><h4>Direcci&oacute;n</h4></center>
				        <hr class="hrForm">
				        <address class="text-primary" id="direccion-info"></address>
					</div>
					<div class="col-md-4">
						<center><h4>Contacto</h4></center>
						<hr class="hrForm">
						<p id="te1">
							<i class="fa fa-phone" ></i> 1:  <span class="text-primary" id="telefono1-info"></span>
						</p>
						<p id="te2">
							<i class="fa fa-phone"></i> 2: <span class="text-primary" id="telefono2-info"></span>
						</p>	
					</div>
					<div class="col-md-4">
						<center><h4>Correos</h4></center>
						<hr class="hrForm">
						<address>
						   	<p id="co1">
								<i class="fa fa-envelope-o" ></i> 1: <a href="mailto:#" style="color: #007eae;"> <span class="text-primary" id="correo1-info"></span></a>
							</p>
							<p id="co2">
								<i class="fa fa-envelope-o"></i> 2:<a href="mailto:#" style="color: #007eae;"> <span class="text-primary" id="correo2-info"></span></a>
							</p>
						</address>
					</div>
				</div>  
				<div class="row">
					<div class="col-md-12 table-responsive">
					<h2>Seleccione una póliza: </h2>
						<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-polizas-vigentes">
							<thead>
								<tr>
									<th>Seleccionar</th>
									<th>Clave</th>
									<th>Producto</th>
									<th>Horas</th>
									<th>Horas Usadas</th>
		<!-- 							<th>F. Inicial</th>
									<th>F. Final</th> -->
									<th>Estado</th>

								</tr>
							</thead>
							<tbody align="center">
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="panel-footer">
		    	<p>Observaciones:</p>
		    	<p><span class="text-primary" id="observaciones_agencia-info"></span></p>
		    	
		    </div>	
		</div>