<br />
<div class="salto"></div>
<div id="alertas">
	
</div>
<div class="panel panel-default">
	<div class="panel-body" id="datos-agencia">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<center>
					<b>
						<span style="color: rgb(255, 255, 255);" class="text-primary" id="nombre_agencia-info"></span>
					</b>
				</center>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-4">
				        <center><h4>Direcci&oacute;n</h4></center>
				        <hr class="hrForm">
				        <address class="text-primary" id="direccion-info"></address>
					</div>
					<div class="col-md-4">
						<center><h4>Contacto</h4></center>
						<hr class="hrForm">
						<p id="te1">
							<i class="fa fa-phone" ></i> 1:  <span class="text-primary" id="telefono1-info"></span>
						</p>
						<p id="te2">
							<i class="fa fa-phone"></i> 2: <span class="text-primary" id="telefono2-info"></span>
						</p>	
					</div>
					<div class="col-md-4">
						<center><h4>Correos</h4></center>
						<hr class="hrForm">
						<address>
						   	<p id="co1">
								<i class="fa fa-envelope-o" ></i> 1: <a href="mailto:#" style="color: #007eae;"> <span class="text-primary" id="correo1-info"></span></a>
							</p>
							<p id="co2">
								<i class="fa fa-envelope-o"></i> 2:<a href="mailto:#" style="color: #007eae;"> <span class="text-primary" id="correo2-info"></span></a>
							</p>
						</address>
					</div>
				</div>  
				<div class="row">
					<div class="col-md-12 table-responsive">
					<h2 class="page-header">Seleccione una póliza: </h2>
						<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-polizas-vigentes">
							<thead>
								<tr>
									<th>Seleccionar</th>
									<th>Clave</th>
									<th>Producto</th>
									<th>Horas</th>
									<th>Horas Restantes</th>
									<th>Estado</th>
								</tr>
							</thead>
							<tbody align="center">
							</tbody>
						</table>
					</div>
				</div>
				<form id="datosFormServicio">
					<h2 class="page-header">Servicio</h2>
					<div class="row">				
		    			<div class="form-group col-md-4">
		    				<label>Solicit&oacute;:</label>
		    				<div class="input-group">
			    			    <select id="solicito" class="form-control"></select>
							    <span class="input-group-btn">
							    	<button class="btn btn-success" type="button" data-dismiss="modal" onclick="" data-toggle="modal" data-target="#nuevoUsuarioModal" id="agregarUsuarioAgenciaBtn">+</button>
							    </span>
						    </div>
							<br/><br/>
		 					<label>Ejecutivo:</label>
		      				<select id="ejecutivo" class="form-control"></select> 
		    			</div>                         
		    			<div class="form-group col-md-4">
							<label>Motivo:</label>
							<select id="motivo" class="form-control">
								<option value="motivo1">Actualizaci&oacute;n</option>
								<option value="motivo2">Configuraci&oacute;n</option>
								<option value="motivo3">Error del Sistema</option>
								<option value="motivo4">Factura Electr&oacute;nica</option>
								<option value="motivo5">Formatos e Impresoras</option>	
								<option value="motivo6">Implementaci&oacute;n</option>
								<option value="motivo7">Informaci&oacute;n</option>
								<option value="motivo8">Instalaci&oacute;n</option>
								<option value="motivo9">Interfases</option>
								<option value="motivo10">Operaci&oacute;n</option>
								<option value="motivo11">Reportarse</option>
								<option value="motivo12">Reportarse Urgentemente</option>
								<option value="motivo13">Reportes</option>
								<option value="motivo14">Seguimiento</option>
						  	</select>
						  	<br/>
							<label>Tipo de Soporte:</label>
							<select id="tipo_soporte" class="form-control">
								<option>Curso</option>
								<option>Demostracion</option>
								<option>Desarrollo</option>
								<option>Implementacion</option>
								<option>Paginas Web</option>
								<option>Reportarse</option>
								<option>Reportarse Urgente</option>
								<option>Revision MIG</option>
								<option>Soporte en Sitio</option>
								<option>Soporte Interno</option>
								<option>Soporte Remoto</option>
								<option>Soporte Telefonico</option>
								<option>Ventas</option>
							</select>							  						
		    			</div>  
		    			<div class="form-group col-md-4">
		      				<label class="control-label">Descripci&oacute;n:</label>
		      				<textarea id="descripcion" class="form-control" rows="5"></textarea>
		    			</div>                  
		  			</div>
				  	<div class="row">
				  		<div class="col-md-10"></div>
				    	<div class="col-md-2">
				      		<button type="button" class="btn btn-outline btn-success btn-lg btn-block" id="submitNuevaOrdenBtn">Guardar</button>
				    	</div>
				  	</div>  					
				</form>
			</div>
			<div class="panel-footer">
					<p>Observaciones:</p>
		    		<p><span class="text-primary" id="observaciones_agencia-info"></span></p>
		    </div>	
		</div>