<br/>
<div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           <div class="panel-heading ">
	                <h1 class="page-header">Administraci&oacute;n de Agencias.</h1>
	           </div>
	           <div class="panel-body">
	            	<div class="panel with-nav-tabs panel-primary">
		                <div class="panel-heading">
		                        <ul class="nav nav-tabs">
		                            <li class="active"><a href="#tab1success" data-toggle="tab">Datos Generales</a></li>
		                            <li><a href="#tab2success" data-toggle="tab">Licencias</a></li>
		                            <li><a href="#tab3success" data-toggle="tab">Configuraciones</a></li>
		                            <li class="dropdown">
		                                <a href="#" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
		                                <ul class="dropdown-menu" role="menu">
		                                    <li><a href="#tab4success" data-toggle="tab">Usuarios</a></li>
		                                    <li><a href="#tab5success" data-toggle="tab">Success 5</a></li>
		                                </ul>
		                            </li>
		                        </ul>
		                </div>
		                <div class="panel-body">
		                    <div class="tab-content">
		                        <div class="tab-pane fade in active" id="tab1success">
									<div class="row">
										<div class="col-md-12">
									        <div class="form-group input-group">
								                <span class="input-group-addon">Nombre Agencia</span>
								                <input type="text" class="form-control" placeholder="Nombre Agencia" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">Nombre Comercial</span>
								                <input type="text" class="form-control" placeholder="Nombre Comercial" id="edita_puesto">
								            </div>
								        </div>
									</div>
									<div class="row">
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Clave de la Agencia</span>
								                <input type="text" class="form-control" placeholder="Clave de la Agencia" id="edita_puesto">
								            </div>
								        </div>
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Adeudo</span>
								                <input type="text" class="form-control" placeholder="Dirección" id="edita_puesto">
								            </div>
										</div>
									</div>
		                        	<div class="row">
										<div class="col-md-4">
									        <h4>Direcci&oacute;n</h4>
									        <div class="form-group input-group">
								                <span class="input-group-addon">Direcci&oacute;n</span>
								                <input type="text" class="form-control" placeholder="Dirección" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">Colonia</span>
								                <input type="text" class="form-control" placeholder="Colonia" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">C.P.</span>
								                <input type="text" class="form-control" placeholder="Código Postal" id="edita_puesto">
								            </div>
								            

									        <address>
									            795 Folsom Ave, Suite 600
									            <br>San Francisco, CA 94107
									        </address>
										</div>
										<div class="col-md-4">
									        <h4>Contacto</h4>
									        <address>
									            <abbr title="Phone">P:</abbr>(123) 456-7890
									            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
									            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
									        </address>
										</div>
										<div class="col-md-4">
											<h4>Correos</h4>
											<address>
											    <a href="mailto:#" style="color: #007eae;">first.last@example.com</a>
											</address>
										</div>
									</div> 		                        
		                        	<div class="row">
										<div class="col-md-4">
									        <h4>Direcci&oacute;n</h4>
									        <address>
									            795 Folsom Ave, Suite 600
									            <br>San Francisco, CA 94107
									        </address>
										</div>
										<div class="col-md-4">
									        <h4>Contacto</h4>
									        <address>
									            <abbr title="Phone">P:</abbr>(123) 456-7890
									            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
									            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
									        </address>
										</div>
										<div class="col-md-4">
											<h4>Correos</h4>
											<address>
											    <a href="mailto:#" style="color: #007eae;">first.last@example.com</a>
											</address>
										</div>
									</div> 
		                        </div>
		                        <div class="tab-pane fade" id="tab2success">Success 2</div>
		                        <div class="tab-pane fade" id="tab3success">Success 3</div>
		                        <div class="tab-pane fade" id="tab4success">Success 4</div>
		                        <div class="tab-pane fade" id="tab5success">Success 5</div>
		                    </div>
		                </div>
		            </div>
	           </div>
	        </div>
	    </div>
	</div>
</div>	    

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<div class="bs-docs-example no-code">
			  Seleccionar: <select class="selectpicker" data-live-search="true" data-width="auto">
					<option>Curso</option>
					<option>Demostracion</option>
					<option>Desarrollo</option>
					<option>Implementacion</option>
					<option>Paginas Web</option>
					<option>Reportarse</option>
					<option>Reportarse Urgente</option>
					<option>Revision MIG</option>
					<option>Soporte en Sitio</option>
					<option>Soporte Interno</option>
					<option>Soporte Remoto</option>
					<option>Soporte Telefonico</option>
					<option>Ventas</option>
			  </select>
			  <button type="button" class="btn btn-outline btn-success btn-lg " onclick="buscar()">Buscar</button>
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>	
	<br/>
	<div class="row" id="datosAgencia" style='display:none;'>
		<div class="col-md-12">
			<div class="panel panel-primary">
                <div class="panel-heading">
                    Nombre de la Agencia
                </div>
                <div class="panel-footer">
                    Observaciones:
                </div>
            </div>
		</div>
	</div>	

<script type="text/javascript">
	function buscar(){
		document.getElementById('datosAgencia').style.display = 'block';
	}
</script>
