<br/>
<div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-info">
	           	<div class="panel-heading ">
	                <h1 class="page-header">Administraci&oacute;n de Agencias.</h1>
	           	</div>
	           	<div class="panel-body">
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-8">
					        <div class="input-group">
							  <span class="input-group-addon">Seleccionar Agencia</span>
							  <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Por favor seleccionar una agencia">
							    <option>Hot Dog, Fries and a Soda</option>
							    <option>Burger, Shake and a Smile</option>
							    <option>Sugar, Spice and all things nice</option>
							    <option>Baby Back Ribs</option>
							    <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
							  </select>
							</div>			
						</div>
						<div class="col-md-2" align="right">
						    <button type="button" class="btn btn-primary btn-circle" data-dismiss="modal" onclick="abrirModalAgregarAgencia()" data-toggle="modal" data-target="#myModal">
						    &nbsp;<i class="fa fa-plus"></i>&nbsp;<i class="fa  fa-plane"></i>&nbsp;
						    </button>							
						</div>
					</div>	
					<br/>
					<div class="well" style="padding-bottom: 0px;padding-top: 0px;">
						<div class="row">
							<div class="col-md-12">
							<center><h2 style="margin-top: 10px;margin-bottom: 0px;">Nombre de la Agencia</h2></center>
							</div>
							<div class="col-md-12">
								<div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px;">
                                	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Tiene Avisos.</b> No cuenta con horas disponibles para servicio .
                            </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-3" style="padding-left: 5px;padding-right: 5px;">
								<div class="bs-callout bs-callout-primary" id="callout-glyphicons-dont-mix" style="min-height: 413px;">
								<h5>Direcci&oacute;n</h5>
									<address>Río Ganges 45, Cuauhtémoc, 06500 Ciudad de México.</address>
									<p><i class="fa fa-phone"></i> 1: </p>
									<p><i class="fa fa-phone"></i> 2: </p>
									<p>RFC: HSBJKFDSJKFSDH</p>
									<p>Ejecutivo Asignado: Pepe</p>
									<p>Ejecutivo Ayuda: Luis</p>
								</div>
							</div>
							<div class="col-md-4" style="padding-left: 5px;padding-right: 5px;">
								<div class="bs-callout bs-callout-primary" id="callout-glyphicons-dont-mix" style="min-height: 413px;">
								<h5 align="center">Configuraci&oacute;n</h5>
								<p>Estatus</p>
								<p>ICAAVWin: Produccion IRISWin: Produccion</p>
								<p>Outsourcing: OQAPDDW Personalizado: Encuesta</p>
								<p>Formatos Pagados Sin documentos</p>
								<p>Factura Elect&oacute;nica: </p>
								<p>Portal Proveedores: N Agencia Consolidada: N Markup: S</p>
								<p>Contabilidad Elect&oacute;nica:S INE:N </p>
								</div>
							</div>
							<div class="col-md-5" style="padding-left: 5px;padding-right: 5px;">
								<div class="bs-callout bs-callout-primary" id="callout-glyphicons-dont-mix">
								<h5 align="center">Productos</h5>
								<div class="row">
									<div class="col-md-3">
										<p align="center">ICAAVWin</p>
									</div>
									<div class="col-md-4">
										<div class="form-group input-group">
						                	<span class="input-group-addon">Lic</span>
						                	<input type="text" class="form-control" value="38" id="edita_puesto" disabled>
						            	</div>
									</div>
									<div class="col-md-5">
										<div class="form-group input-group">
						                	<span class="input-group-addon">AnyWhere</span>
						                	<input type="text" class="form-control" value="2" id="edita_puesto" disabled>
						            	</div>	
									</div>							
								</div>
								<div class="row">
									<div class="col-md-3">
										<p align="center">IRISWin</p>
									</div>
									<div class="col-md-4">
										<div class="form-group input-group">
						                	<span class="input-group-addon">Lic</span>
						                	<input type="text" class="form-control" value="38" id="edita_puesto" disabled>
						            	</div>
									</div>
									<div class="col-md-5">
										<div class="form-group input-group">
						                	<span class="input-group-addon">AnyWhere</span>
						                	<input type="text" class="form-control" value="2" id="edita_puesto" disabled>
						            	</div>	
									</div>							
								</div>								
								<div class="row">
									<div class="col-md-3">
										<p align="center">Centauro</p>
									</div>
									<div class="col-md-4">
										<div class="form-group input-group">
						                	<span class="input-group-addon">Lic</span>
						                	<input type="text" class="form-control" value="38" id="edita_puesto" disabled>
						            	</div>
									</div>
									<div class="col-md-5">
										<div class="form-group input-group">
						                	<span class="input-group-addon">AnyWhere</span>
						                	<input type="text" class="form-control" value="2" id="edita_puesto" disabled>
						            	</div>	
									</div>							
								</div>
								<div class="row">
									<div class="col-md-3">
										<p align="center">GVC</p>
									</div>
									<div class="col-md-4">
										<div class="form-group input-group">
						                	<span class="input-group-addon">Lic</span>
						                	<input type="text" class="form-control" value="38" id="edita_puesto" disabled>
						            	</div>
									</div>
									<div class="col-md-5">
										<div class="form-group input-group">
						                	<span class="input-group-addon">AnyWhere</span>
						                	<input type="text" class="form-control" value="2" id="edita_puesto" disabled>
						            	</div>	
									</div>							
								</div>															
								<p>Globalizador: SA, WS </p>
								<p>Producto: icaavwin</p>
								<p>Implant AM: N</p>
								<p>Version PB: 11  FE: CFDI Timbrado: E Boleto-E: S</p>
								<p>Facturaci&oacute; de Boletos: Layout MIG y EDICOM Precio: MIG</p>
								</div>
							</div>
						</div>
					</div>
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-agencias">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre</th>
								<th>Estatus</th>
								<th>Correo</th>
								<th>Detalles</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->registros as $registro) { ?>
							<tr
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_usuario'] ?></td>
								<td><?php echo $registro['clave'] ?></td>
								<td><?php echo $registro['nombre'] ?> <?php echo $registro['apellido_paterno'] ?> <?php echo $registro['apellido_materno'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 'S' ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td><?php echo $registro['email'] ?></td>
								<td>
									<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" value='<?= json_encode($registro) ?>'
									onclick="datosform_edita_usuario(this.value)">
									<i class="fa fa-info-circle"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
	        </div>
	    </div>
	</div>
</div>	    
	<div class="row" id="datosAgencia" style='display:none;'>
		<div class="col-md-12">
			<div class="panel panel-primary">
                <div class="panel-heading">
                    Nombre de la Agencia
                </div>
                <div class="panel-footer">
                    Observaciones:
                </div>
            </div>
		</div>
	</div>	

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 	<div class="modal-dialog modal-lg" role="document">
   		<div class="modal-content">
		    <div class="modal-header">
		     	<div class="row">
		    		<div class="col-md-10">
						<h4 class="modal-title" id="myModalLabel"></h4>
		    		</div>
		    		<div class="col-md-2" align="right">
		       			<button type="button" class="btn btn-info btn-circle" data-dismiss="modal"><i class="fa fa-times"></i></button>
		    		</div> 			    		
		    	</div>
		    </div>
		    <div class="modal-body">
	           	<div class="panel-body">
	            	<div class="panel with-nav-tabs panel-primary">
		                <div class="panel-heading">
		                        <ul class="nav nav-tabs">
		                            <li class="active"><a href="#tabGenerales" data-toggle="tab">Datos Generales</a></li>
		                            <li><a href="#tabContacto" data-toggle="tab">Contacto</a></li>
		                            <li><a href="#tabLicencias" data-toggle="tab">Licencias</a></li>
		                            <li><a href="#tabConfiguraciones" data-toggle="tab">Configuraciones</a></li>
		                            <li class="dropdown">
		                                <a href="#" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
		                                <ul class="dropdown-menu" role="menu">
		                                    <li><a href="#tab4success" data-toggle="tab">Usuarios</a></li>
		                                    <li><a href="#tab5success" data-toggle="tab">Success 5</a></li>
		                                </ul>
		                            </li>
		                        </ul>
		                </div>
		                <div class="panel-body">
		                    <div class="tab-content">
		                        <div class="tab-pane fade in active" id="tabGenerales">
									<div class="row">
										<div class="col-md-12">
									        <div class="form-group input-group">
								                <span class="input-group-addon">Nombre Agencia</span>
								                <input type="text" class="form-control" placeholder="Nombre Agencia" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">Nombre Comercial</span>
								                <input type="text" class="form-control" placeholder="Nombre Comercial" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">RFC</span>
								                <input type="text" class="form-control" placeholder="RFC" id="edita_puesto">
								            </div>
								        </div>
									</div>
									<div class="row">
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Clave de la Agencia</span>
								                <input type="text" class="form-control" placeholder="Clave de la Agencia" id="edita_puesto">
								            </div>
								        </div>
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Adeudo</span>
								                <input type="text" class="form-control" placeholder="Adeudo" id="edita_puesto">
								            </div>
										</div>
									</div>
									<div class="row">
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Ejecutivo Titular</span>
								                <input type="text" class="form-control" placeholder="Titular" id="edita_puesto">
								            </div>
								        </div>
								        <div class="col-md-6">
								            <div class="form-group input-group">
								                <span class="input-group-addon">Ejecutivo Auxiliar</span>
								                <input type="text" class="form-control" placeholder="Auxiliar" id="edita_puesto">
								            </div>
										</div>
									</div>									
								</div>
								<div class="tab-pane fade" id="tabContacto">	
		                        	<div class="row">
										<div class="col-md-4">
									        <h4>Direcci&oacute;n</h4>
									        <div class="form-group input-group">
								                <span class="input-group-addon">Direcci&oacute;n</span>
								                <input type="text" class="form-control" placeholder="Dirección" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">Colonia</span>
								                <input type="text" class="form-control" placeholder="Colonia" id="edita_puesto">
								            </div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">C.P.</span>
								                <input type="text" class="form-control" placeholder="Código Postal" id="edita_puesto">
								            </div>
										</div>
										<div class="col-md-4">
									        <h4>Contacto</h4>
									        <div class="row">
												<div class="col-md-12">
											        <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-phone"></i> 1</span>
										                <input type="text" class="form-control" placeholder="Teléfono 1" id="edita_puesto">
										            </div>
											        <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-phone"></i> 2</span>
										                <input type="text" class="form-control" placeholder="Teléfono 2" id="edita_puesto">
										            </div>
										            <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-fax"></i></span>
										                <input type="text" class="form-control" placeholder="Fax" id="edita_puesto">
										            </div>
										        </div>
											</div>
										</div>
										<div class="col-md-4">
											<h4>Correos</h4>
											<div class="row">
												<div class="col-md-12">
											        <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-envelope-o"></i> 1</span>
										                <input type="text" class="form-control" placeholder="Correo 1" id="edita_puesto">
										            </div>
										            <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-envelope-o"></i> 2</span>
										                <input type="text" class="form-control" placeholder="Correo 2" id="edita_puesto">
										            </div>
										            <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
										                <input type="text" class="form-control" placeholder="Sitio Web" id="edita_puesto">
										            </div>
										        </div>
										    </div>
										</div>
									</div> 		                        
		                        </div>
		                        <div class="tab-pane fade" id="tabLicencias">
									<div class="col-md-4">
									<h4>Licencias</h4>
								        <div class="form-group input-group">
							                <span class="input-group-addon">ICAAVWin</span>
							                <input type="text" class="form-control" placeholder="ICAAVWin" id="edita_puesto">
							            </div>
							            <div class="form-group input-group">
							                <span class="input-group-addon">IRISWin</span>
							                <input type="text" class="form-control" placeholder="IRISWin" id="edita_puesto">
							            </div>
							            <div class="form-group input-group">
							                <span class="input-group-addon">Centauro</span>
							                <input type="text" class="form-control" placeholder="Centauro" id="edita_puesto">
							            </div>
							            <div class="form-group input-group">
									                <span class="input-group-addon">GVC</span>
									                <input type="text" class="form-control" placeholder="GVC" id="edita_puesto">
									    </div>
									</div>
									<div class="col-md-4">
								        <div class="row">
								        <h4>AnyWhere</h4>
											<div class="col-md-12">
										        
										        <div class="form-group input-group">
									                <span class="input-group-addon">AnyWhere</span>
									                <input type="text" class="form-control" placeholder="AnyWhere" id="edita_puesto">
									            </div>
									            <div class="form-group input-group">
									                <span class="input-group-addon">IRISWin</span>
									                <input type="text" class="form-control" placeholder="IRISWin" id="edita_puesto">
									            </div>
									            <div class="form-group input-group">
									                <span class="input-group-addon">Centauro</span>
									                <input type="text" class="form-control" placeholder="Centauro" id="edita_puesto">
									            </div> 
									            <div class="form-group input-group">
									                <span class="input-group-addon">GVC</span>
									                <input type="text" class="form-control" placeholder="GVC" id="edita_puesto">
									            </div>      
									        </div>
										</div>
									</div>
									<div class="col-md-4">
										<h4>Correos</h4>
										<div class="row">
											<div class="col-md-12">
										        <div class="form-group input-group">
									                <span class="input-group-addon">Formatos Pagados</span>
									                <input type="text" class="form-control" placeholder="Correo 1" id="edita_puesto">
									            </div>
									            <div class="form-group input-group">
									                <span class="input-group-addon"><i class="fa fa-envelope-o"></i> 2</span>
									                <input type="text" class="form-control" placeholder="Correo 2" id="edita_puesto">
									            </div>
									            <div class="form-group input-group">
									                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
									                <input type="text" class="form-control" placeholder="Sitio Web" id="edita_puesto">
									            </div>
									        </div>
									    </div>
									</div>
								</div> 			                        	
		                        <div class="tab-pane fade" id="tabConfiguraciones">
		                        	<div class="row">
										<div class="col-md-4">
									        <h4>Estatus</h4>
								            <div class="input-group">
											  <span class="input-group-addon">ICAAVWin</span>
											  <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Please select a lunch ...">
											    <option>Hot Dog, Fries and a Soda</option>
											    <option>Burger, Shake and a Smile</option>
											    <option>Sugar, Spice and all things nice</option>
											    <option>Baby Back Ribs</option>
											    <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
											  </select>
											</div>
											<div class="input-group">
											  <span class="input-group-addon">IRISWin</span>
											  <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Please select a lunch ...">
											    <option>Hot Dog, Fries and a Soda</option>
											    <option>Burger, Shake and a Smile</option>
											    <option>Sugar, Spice and all things nice</option>
											    <option>Baby Back Ribs</option>
											    <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
											  </select>
											</div>
								            <div class="form-group input-group">
								                <span class="input-group-addon">MCL</span>
								                <input type="text" class="form-control" placeholder="Código Postal" id="edita_puesto">
								            </div>
										</div>
										<div class="col-md-4">
									        <h4>Datos</h4>
									        <div class="row">
												<div class="col-md-12">
											        <div class="form-group input-group">
										                <span class="input-group-addon">Versi&oacute;n ICAAV</span>
										                <input type="text" class="form-control" placeholder="Versión ICAAV" id="edita_puesto">
										            </div>
											        <div class="form-group input-group">
										                <span class="input-group-addon">No. Serie</span>
										                <input type="text" class="form-control" placeholder="No. Serie" id="edita_puesto">
										            </div>
										            <div class="form-group">
			                                            <label>Interface</label>
			                                            <div class="row">
			                                            	<div class="col-md-6">
			                                            		<div class="input-group">
												                    <span class="input-group-addon beautiful">
												                        <input type="checkbox">
												                    </span>
												                    <input type="text" class="form-control" value="Amadeus">
												                </div>
													            <div class="input-group">
												                    <span class="input-group-addon beautiful">
												                        <input type="checkbox">
												                    </span>
												                    <input type="text" class="form-control" value="Sabre">
												                </div>
			                                            	</div>
			                                            	<div class="col-md-6">
					                                            <div class="input-group">
												                    <span class="input-group-addon beautiful">
												                        <input type="checkbox">
												                    </span>
												                    <input type="text" class="form-control" value="Apollo">
												                </div>		
					                                            <div class="input-group">
												                    <span class="input-group-addon beautiful">
												                        <input type="checkbox">
												                    </span>
												                    <input type="text" class="form-control" value="Wordspan">
												                </div>	                	                                            		
			                                            	</div>
			                                            </div>
			                                        </div>
										        </div>
											</div>
										</div>
										<div class="col-md-4">
											<h4>Facturas</h4>
											<div class="row">
												<div class="col-md-12">
										            <div class="input-group">
													  <span class="input-group-addon">Factura Electr&oacute;nica</span>
													  <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Please select a lunch ...">
													    <option>Hot Dog, Fries and a Soda</option>
													    <option>Burger, Shake and a Smile</option>
													    <option>Sugar, Spice and all things nice</option>
													    <option>Baby Back Ribs</option>
													    <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
													  </select>
													</div>
													<div class="input-group">
									                    <span class="input-group-addon beautiful">
									                        <input type="checkbox">
									                    </span>
									                    <input type="text" class="form-control" value="CFDI">
									                </div>
									                <div class="input-group">
													  <span class="input-group-addon">Timbrado</span>
													  <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Please select a lunch ...">
													    <option>Hot Dog, Fries and a Soda</option>
													    <option>Burger, Shake and a Smile</option>
													    <option>Sugar, Spice and all things nice</option>
													    <option>Baby Back Ribs</option>
													    <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
													  </select>
													</div>	
										            <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-envelope-o"></i> 2</span>
										                <input type="text" class="form-control" placeholder="Correo 2" id="edita_puesto">
										            </div>
										            <div class="form-group input-group">
										                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
										                <input type="text" class="form-control" placeholder="Sitio Web" id="edita_puesto">
										            </div>
										        </div>
										    </div>
										</div>
									</div> 		                        	
		                        </div>
		                        <div class="tab-pane fade" id="tab4success">Success 4</div>
		                        <div class="tab-pane fade" id="tab5success">Success 5</div>
		                    </div>
		                </div>
		            </div>
	           </div>
	        </div>
   		</div>
 	</div>
</div>





<script type="text/javascript">
	function buscar(){
		document.getElementById('datosAgencia').style.display = 'block';
	}
</script>
