<link rel="stylesheet" type="text/css" href="public/css/flipclock.css">
<h1 class="page-header">Seguimiento Ordenes de Servicio Admin</h1>
<div class="row">
	<table width="100%" class="table">
		<thead>
			<tr>
				<th class="amarillo centrado">Lamada sin Contestar</th>
				<th class="naranja centrado">Reportarse</th>
				<th class="rojo centrado">Reportarse Urgente</th>
				<th class="centrado">Otros Servicios</th>
				<th class="morado centrado">Externos</th>		
			</tr>
		</thead>	
	</table>
</div>
<form class="form-inline" method="get" name="filtroform" id="filtroform">
</form>

<div class="alert alert-info alert-dismissable">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<h3 style="margin-top: 0px;margin-bottom: 0px;">Se muestra(n) <b id="total_ordenes"></b> resultado(s):</h3>
</div>

<div class="row">
	<div class="col-md-12">


<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
	<?php $id_orden_servicio_todos=","?>
	<?php $duracion_servicio_todos=","?>
	<?php $control_cron_estatus_todos=","?>
	<?php $motivo_todos=","?>
  	<?php foreach ($this->paginator as $registro) { 
  		$color='';

		if($registro['control_cron_estatus']!=0){
  		switch ($registro["id_orden_servicio_estatus"]){
  			case '1':
  				$color='bs-callout-amarillo-verde';
  			break;
  			case '2':
  				$color='bs-callout-naranja-verde';
  			break;
  			case '3':
  				$color='bs-callout-rojo-verde';
  			break;
  			case '4':
  				$color='bs-callout-gris-verde';
  			break;
  			case '5':
  				$color='bs-callout-morado-verde';
  			break;
  		}
		}else{
  		switch ($registro["id_orden_servicio_estatus"]){
  			case '1':
  				$color='bs-callout-amarillo';
  			break;
  			case '2':
  				$color='bs-callout-naranja';
  			break;
  			case '3':
  				$color='bs-callout-rojo';
  			break;
  			case '4':
  				$color='bs-callout-gris';
  			break;
  			case '5':
  				$color='bs-callout-morado';
  			break;
  		}		
		}


  		if($registro["control_cron_estatus"]!=3){
  		?>
	
		<div id="orden_servicio_<?= $registro["id_orden_servicio"]?>" class="panel panel-default bs-callout2 <?= $color ?>">
		 	<div class="panel-heading <?= $color ?>2">
            	<b>
            	<div class="row">
            		<div class="col-md-9">
            			<center><?= $registro["agencia_nombre"] ?></center>
            		</div>
            		<div class="col-md-3" align="right">
            			ID Orden Servicio: <?= $registro["id_orden_servicio"].'-'.$registro["id_orden_servicio_estatus"]?>
            		</div>
            	</div>
            	</b>
            </div>
		 	<div class="panel-body">
			 	<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label >Fecha Solicitud:</label>
                            <input id="fecha_solicitud_<?= $registro["id_orden_servicio"]?>" class="form-control" value="<?= $registro["fecha_alta"] ?>" disabled>
                        </div>
					  	<div class="form-group">
					  		<label>Fecha Respuesta:</label>
					  		<input id="fecha_respuesta_<?= $registro["id_orden_servicio"]?>" class="form-control" value="____-__-__  __:__:__" data-mask="____-__-__  __:__:__">
					  	</div>                        
 						<div class="form-group">
                            <label>Producto:</label>
							<p></p>
                        </div>                                              
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="form-group">
                            <label>Usuario Solicitante:</label>
                            <input id="solicito_<?= $registro["id_orden_servicio"]?>" class="form-control" value="<?= $registro["usuario_agencia_nombre"] ?> <?= $registro["usuario_agencia_apellidos"] ?>">
							
                        </div>
 						<div class="form-group">
                            <label>Usuario Atenci&oacute;n:</label>
                            <input id="atendio_<?= $registro["id_orden_servicio"]?>" class="form-control" value="<?= $registro["clave"] ?>">
                        </div>    
					</div>
					<div class="col-lg-3 col-md-6">
 						<div class="form-group">
                            <label>Comentarios Recepci&oacute;n:</label>
							<p><?= $registro["comentarios_recepcion"] ?></p>
                        </div>   
                        <div class="form-group">
                            <label>Descripci&oacute;n / Soporte:</label>
				  			<p><?= $registro["descripcion"] ?></p>
                        </div>   
					</div>
					<div class="col-lg-3 col-md-6">
	                    <!-- AQUI ES EL CRONOMETRO -->


	                    <div class="panel <?= $color ?>2" >
	                        <div class="panel-heading">
								<label class="control-label">Duraci&oacute;n del Servicio</label>
								<input id="duracion_<?= $registro["id_orden_servicio"]?>" class="form-control" value="__:__:__" data-mask="__:__:__" style="text-align:center; font-size: x-large;">
	                        </div>
	                    </div>
	                    <div align="right">
	                    <a class="btn <?= $color ?>2" href="#orden_<?= $registro["id_orden_servicio"]?>" data-toggle="collapse"><i class="fa fa-chevron-down"></i></a></div>
	                </div>
				</div>
			  	  

				<hr style=" margin-top: 5px; margin-bottom: 10px;">	



				<div id="orden_<?= $registro["id_orden_servicio"]?>" class="collapse">
					<div class="row">
					  	<div class="col-md-6 form-group">
				  				<label>Motivo:</label>
					  			<textarea id="motivo_<?= $registro["id_orden_servicio"]?>" class="form-control" rows="3" value="<?= $registro["motivo"] ?>"><?= $registro["motivo"] ?></textarea>							  			
					  	</div>
					  	<div class="col-md-6 form-group">
					  		<label>Solución:</label>
					  		<textarea id="solucion_<?= $registro["id_orden_servicio"]?>" class="form-control" rows="3" value="<?= $registro["solucion"] ?>"><?= $registro["solucion"] ?></textarea>
					  	</div>				  	
					</div>
				  	<br/>
				  	<hr style=" margin-top: 5px; margin-bottom: 10px;">	  		    
				  	<div class="row">
					  	<div class="col-md-6 form-group">
					  		<label>Conformidad:</label>
					  		<input id="conformidad_<?= $registro["id_orden_servicio"]?>" class="form-control">
					  	</div>
					  	<div class="col-md-6">
					  		<div class="row">
					  			<div class="col-md-3 form-group">

					  			</div>
					  			<div class="col-md-2 form-group">
					  				<label></label>
					  				<button id="guardarServicio_<?= $registro["id_orden_servicio"] ?>" onclick="guardarSercicioAjax(this.id)" type="button" class="btn btn-primary">Guardar Servicio</button>
					  			</div>
								<div class="col-md-2"></div>
					  			<div class="col-md-2 form-group">
					  				<label></label>
					  				<button id="concluirServicio_<?= $registro["id_orden_servicio"] ?>" onclick="concluirSercicioAjax(this.id)" type="button" class="btn btn-primary">Servicio Concluido</button>
					  				
					  			</div>					  			
					  			<div class="col-md-3"></div>
					  		</div>
					  	</div>
					  	<div class="col-md-2"></div>			  				  	
				  	</div>	
				</div>
		  </div>
		</div>

		<?php $id_orden_servicio_todos = $id_orden_servicio_todos . $registro["id_orden_servicio"] . ","  ?>
		<?php $duracion_servicio_todos = $duracion_servicio_todos . $registro["duracion_servicio"] . ","  ?>
		<?php $control_cron_estatus_todos = $control_cron_estatus_todos . $registro["control_cron_estatus"] . ","  ?>
		<?php $motivo_todos = $motivo_todos . $registro["motivo"] . ","  ?>
	
	<?php 
		}
	} ?>
	<p id="info_id_ordenes" hidden="true"> <?= $id_orden_servicio_todos ?> </p>
	<p id="info_duracion_servicio_todos" hidden="true"> <?= $duracion_servicio_todos ?> </p>
	<p id="info_control_cron_estatus_todos" hidden="true"> <?= $control_cron_estatus_todos ?> </p>
	<p id="info_motivo_todos" hidden="true"> <?= $motivo_todos ?> </p>
	</div>
	
	<div class="row" align="right">
	<?=$this->paginationControl ($this->paginator, 'Sliding');?>
</div>
</div>


