<h1 class="page-header">Nueva Orden de Servicio</h1>

<div class="row">
	<div class="col-md-3">
		
	</div>
	<div class="col-md-6">
		<div class="bs-docs-example no-code">
		  Soporte: <select class="selectpicker" data-live-search="true" data-width="auto">
				<option>Curso</option>
				<option>Demostracion</option>
				<option>Desarrollo</option>
				<option>Implementacion</option>
				<option>Paginas Web</option>
				<option>Reportarse</option>
				<option>Reportarse Urgente</option>
				<option>Revision MIG</option>
				<option>Soporte en Sitio</option>
				<option>Soporte Interno</option>
				<option>Soporte Remoto</option>
				<option>Soporte Telefonico</option>
				<option>Ventas</option>
		  </select>
		</div>
	</div>	
	<div class="col-md-3">
	</div>
</div>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="bs-docs-example no-code">
		  Agencia: <select class="selectpicker" data-live-search="true" data-width="auto">
				<option>DOS PUERTAS Y LANCERS</option>
				<option>DOUBLETREE HOTELS</option>
				<option>DOVER DE MEXICO, S.A. DE C.V.</option>
				<option>DOW CORNING DE MEXICO,   S.A. DE C.V.</option>
				<option>DOW CORNING DE MEXICO,   S.A. DE C.V.   </option>
				<option>DOW JONES TELERATE FINANCIAL INFORMATION SERVICES, INC</option>
				<option>DOW QUIMICA MEXICANA, S.A. DE C.V.</option>
				<option>DOWEL SCHLUMBERGER DE MEXICO, S.A. DE C.V.</option>  
				<option>DR JOSE POLAK, S.A. DE C.V.</option>
				<option>DR. FRANCISCO SANTINI Y ASOCIADOS</option>
				<option>DRAGOCO, S.A.</option>
				<option>DRESDNER BANK MEXICO, S.A.</option>
				<option>OFICINAS CORPORATIVAS</option>
				<option>EDUARDO VEGA Y COMPAÑIA, SUCESORES, S.A. DE C.V.</option>
				<option>EDUCACION PSICOLOGIA Y SALUD,  A.C.</option>
				<option>EDUCAL, S.A. DE C.V.</option>
				<option>EF SERVICIOS EN EDUCACION INTERNACIONAL, S.A. DE C.V.</option>
				<option>EFECTIVALE, S.A. DE C.V.</option>
				<option>EFFIX, S.A. DE C.V.</option>
				<option>EFFORT DE MEXICO, S.A. DE C.V.</option>
				<option>EGON MEYER, S.A. DE C.V.</option>
				<option>EIF LUBRICANTES MEXICO, S.A. DE C.V.</option>
				<option>EJECUTIVOS Y ASESORES EN TURISMO</option>
				<option>EJES TRACTIVOS, S.A. DE C.V.</option>
				<option>EKONOM,  S.A. DE C.V.</option>
				<Option>EQUIPO INDUSTRIAL "RYMACH"</Option>
				<Option>EQUIPO PARA EMBOTELLADORAS Y CERVECERIAS, S.A. DE C.V.</option>
				<Option>EQUIPOS AUTOMOTRICES NACIONALES, S.A. DE C.V.</option>
				<Option>EQUIPOS BIOMEDICOS PROFESIONALES,  S.A. DE C.V.</option>
				<Option>EQUIPOS COMPUTACIONALES DE MEXICO, S.A. DE C.V.</option>
				<Option>EQUIPOS DE TELECOMUNICACIONES Y REDES,  S.A. DE C.V.</option>
				<Option>EQUIPOS E INSTRUMENTAL MEDICO QUIRURGICO, S.A. DE C.V.</option>
				<Option>EQUIPOS ELECTROMECANICOS, S.A. DE C.V.</option>
				<Option>EQUIPOS ELECTRO-MEDICOS REQUENA,  S.A. DE C.V.</option>
				<Option>EQUIPOS INDUSTRIALES DE LIMPIEZA,  S.A. DE C.V.</option>
				<Option>EQUIPOS INTERFERENCIALES DE MEXICO</option>
				<Option>ESCUELA DE PERIODISMO CARLOS SEPTIEN GARCIA</option>
				<Option>ESCUELA INTERNACIONAL DE TURISMO</option>
				<Option>ESCUELA LIBRE DE DERECHO</option>
				<Option>ESCUELA NACIONAL DE CIENCIAS BIOLOGICAS</option>
				<Option>ESCUELA NACIONAL DE MEDICINA Y HOMEOPATIA ( IPN )</option>
				<Option>ESCUELA PANAMERICANA DE HOTELERIA, A.C.</option>
				<Option>ESCUELA SUPERIOR DE COMERCIO Y ADMON.</option>
		  </select>
		</div>
	</div>	
	<div class="col-md-3"></div>
</div>
<br />


<div class="panel panel-primary">
	<div class="panel-heading">
	<b>Nombre de la Agencia</b>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
		        <h4>Direcci&oacute;n</h4>
		        <address>
		            795 Folsom Ave, Suite 600
		            <br>San Francisco, CA 94107
		        </address>
			</div>
			<div class="col-md-4">
		        <h4>Contacto</h4>
		        <address>
		            <abbr title="Phone">P:</abbr>(123) 456-7890
		            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
		            <br /><abbr title="Phone">Tel:</abbr>(123) 456-7890
		        </address>
			</div>
			<div class="col-md-4">
				<h4>Correos</h4>
				<address>
				    <a href="mailto:#" style="color: #007eae;">first.last@example.com</a>
				</address>
			</div>
		</div>  
		<div class="row">
			<div class="col-md-12 table-responsive">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
					<thead>
						<tr>
							<th>Clave</th>
							<th>Horas</th>
							<th>H.ICAAV</th>
							<th>H. Iris</th>
							<th>Cantidad</th>
							<th>F. Inicial</th>
							<th>F. Final</th>
							<th>Agotado</th>
							<th>Garantia</th>
						</tr>
					</thead>
					<tbody align="center">
						<tr>
							<td>JOMKMR</td>
							<td>30</td>
							<td>30</td>
							<td>0</td>
							<td>0</td>
							<td>18/02/2016</td>
							<td>17/02/2020</td>
							<td>N</td>
							<td>N</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 table-responsive">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
					<thead>
						<tr>
							<th>Descripci&oacute;n</th>
							<th>Actualiza</th>
							<th>Telef&oacute;nico</th>
							<th>Temoto</th>
							<th>Conv. L.A.</th>
							<th>01800</th>
							<th>Sitio</th>
							<th>BSP Link</th>
							<th>Factura E</th>
						</tr>
					</thead>
					<tbody align="center">
						<tr>
							<td>Premium</td>
							<td>X</td>
							<td>X</td>
							<td>X</td>
							<td>X</td>
							<td>X</td>
							<td>X</td>
							<td>X</td>
							<td>ICAAVWin</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="panel-footer">
    	<p>Observaciones:<object align="right"><b>Tiempo Restante: ??:??</b></object></p><br/>
    	
    </div>	
</div>

<div class="panel panel-primary">
	<div class="panel-heading">
	<b>Servicio</b>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<div class="bs-docs-example no-code">
				  Producto: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>
				<div class="bs-docs-example no-code">
				  Solicit&oacute;: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>					        
			</div>
			<div class="col-md-4">
				<div class="bs-docs-example no-code">
				  Ejecutivo: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div><br/>			
				<div class="bs-docs-example no-code">
				  Motivo: <select class="selectpicker" data-live-search="true" data-width="auto">
						<option>Curso</option>
						<option>Demostracion</option>
						<option>Desarrollo</option>
				  </select>
				</div>			        
			</div>			
			<div class="col-md-4">
				Descripci&oacute;n: <textarea class="form-control" rows="3"></textarea>			        
			</div>
		</div>
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<button type="button" class="btn btn-outline btn-success btn-lg btn-block" onclick="">Guardar</button>
			</div>
			<div class="col-md-4"></div>
		</div>		
    </div>
</div>
