<style>
	th, td {
    	padding-top: 5px !important;
    	padding-bottom: 5px !important;
	}
	.panel-heading {
    	padding-top: 7px !important;
    	padding-bottom: 7px !important;
	}
</style>


<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <center>Monitoreo de Llamadas</center>
    </div>
    <div class="panel-body">
		<div class="row">
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 1
				    </div>
				    <div class="panel-body" style="min-height: 150px;padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr class="warning">
										<td>2</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr>
										<td>3</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 2
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 3
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 1
				    </div>
				    <div class="panel-body" style="min-height: 150px;padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr class="warning">
										<td>2</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr>
										<td>3</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 2
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 3
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 1
				    </div>
				    <div class="panel-body" style="min-height: 150px;padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr class="warning">
										<td>2</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr>
										<td>3</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 2
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 3
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 1
				    </div>
				    <div class="panel-body" style="min-height: 150px;padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr class="warning">
										<td>2</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
									<tr>
										<td>3</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 2
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4" style="padding-left: 0px;padding-right: 0px;">
				<div class="panel panel-info">
				    <div class="panel-heading">
				        Nombre 3
				    </div>
				    <div class="panel-body" style="min-height: 150px; padding-left: 5px;padding-bottom: 5px;padding-top: 5px;padding-right: 5px;">
						<div class="table-responsive">
							<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios" style="font-size:10px">
								<thead>
									<tr>
										<th>#</th>
										<th>Fecha</th>
										<th>Hora</th>
										<th>Agencia</th>
										<th>Solicito</th>
										<th>Reporte</th>
									</tr>
								</thead>
								<tbody align="center">
									<tr>
										<td>1</td>
										<td>30/09/2016</td>
										<td>12:30</td>
										<td>Viajes Villa</td>
										<td>German Villa</td>
										<td>1RS52</td>
									</tr>
								</tbody>
							</table>
						</div>
				    </div>
				</div>
			</div>
		</div>						
    </div>
</div>



