<h1 class="page-header">Nueva Orden de Servicio</h1>

<div class="row">
	<div class="col-md-1">
		
	</div>
	<div class="col-md-4">
		<div class="input-group">
		  	<label>Buscar Agencia:</label> <?= $this->selectAgencias->select_agencias?>
		</div>
	</div>
	<div class="col-md-2"></div>
	<div class="col-md-4">
		<div class="input-group">
		  	<label>Tipo de Soporte:</label>
		  	<select class="selectpicker" data-live-search="true" data-width="auto">
				<option>Curso</option>
				<option>Demostracion</option>
				<option>Desarrollo</option>
				<option>Implementacion</option>
				<option>Paginas Web</option>
				<option>Reportarse</option>
				<option>Reportarse Urgente</option>
				<option>Revision MIG</option>
				<option>Soporte en Sitio</option>
				<option>Soporte Interno</option>
				<option>Soporte Remoto</option>
				<option>Soporte Telefonico</option>
				<option>Ventas</option>
		  </select>			
		</div>
	</div>	
	<div class="col-md-1"></div>
</div>
<br />
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    Tiene adeudo en ICAVVwin
</div>
<div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    Tiene 1 pago por evento
</div>
<div class="salto"></div>
<div class="panel panel-default">
	<div class="panel-body" id="datos-agencia">
		<?= $this->render('ordenes/render-nueva-orden/datosAgencia.phtml') ?>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-body" id="datos-servicio">
		<?= $this->render('ordenes/render-nueva-orden/servicio.phtml') ?>
	</div>
</div>

