<h1 class="page-header">Seguimiento Ordenes de Servicio</h1>


<div class="row">
	<div class="col-md-10"></div>
	<div class="col-md-2 table-responsive">
		<table width="100%" class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th class="amarillo">&nbsp;&nbsp;&nbsp;&nbsp;</th>
					<th>Lamadas sin Contestar</th>
				</tr>
			</thead>
			<tbody align="center" id="body-ts">
				<tr>
					<th class="naranja"></th>
					<th>Reportarse</th>
				</tr>
				<tr>
					<th class="rojo"></th>
					<th>Reportarse Urgente</th>
				</tr>
				<tr>
					<th class=""></th>
					<th>Otros Servicios</th>
				</tr>
				<tr>
					<th class="morado"></th>
					<th>Externos</th>
				</tr>				
			</tbody>		
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-12 table-responsive">
		<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-seguimientoOrdenes">
			<thead>
				<tr>
					<th>Fecha</th>
					<th>Hora</th>
					<th>Producto</th>
					<th>Soporte</th>
					<th>Solicit&oacute;</th>
					<th>Empresa</th>
					<th>Motivo</th>
					<th>Ejecutivo</th>
					<th>Licencia</th>
					<th>Reporte</th>
				</tr>
			</thead>
			<tbody align="center" id="body-ts">
				<tr class="amarillo">
					<th>12/11/2016</th>
					<th>17:00</th>
					<th>icaavwin</th>
					<th>telefono</th>
					<th>Angelica Ruiz</th>
					<th>gpodestinos</th>
					<th>Problema Operativo</th>
					<th>Arturo de la Cruz</th>
					<th>3123312</th>
					<th>876543</th>
				</tr>
				<tr class="naranja">
					<th>12/11/2016</th>
					<th>17:00</th>
					<th>icaavwin</th>
					<th>telefono</th>
					<th>Angelica Ruiz</th>
					<th>gpodestinos</th>
					<th>Problema Operativo</th>
					<th>Arturo de la Cruz</th>
					<th>3123312</th>
					<th>876543</th>
				</tr>
				<tr class="rojo">
					<th>12/11/2016</th>
					<th>17:00</th>
					<th>icaavwin</th>
					<th>telefono</th>
					<th>Angelica Ruiz</th>
					<th>gpodestinos</th>
					<th>Problema Operativo</th>
					<th>Arturo de la Cruz</th>
					<th>3123312</th>
					<th>876543</th>
				</tr>
				<tr class="morado">
					<th>12/11/2016</th>
					<th>17:00</th>
					<th>icaavwin</th>
					<th>telefono</th>
					<th>Angelica Ruiz</th>
					<th>gpodestinos</th>
					<th>Problema Operativo</th>
					<th>Arturo de la Cruz</th>
					<th>3123312</th>
					<th>876543</th>
				</tr>				
				<tr>
					<th>12/11/2016</th>
					<th>17:00</th>
					<th>icaavwin</th>
					<th>telefono</th>
					<th>Angelica Ruiz</th>
					<th>gpodestinos</th>
					<th>Problema Operativo</th>
					<th>Arturo de la Cruz</th>
					<th>3123312</th>
					<th>876543</th>
				</tr>				
			</tbody>
		</table>		
	</div>
</div>


