<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Administraci&oacute;n de usuarios.</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<a class="btn btn-success" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Agregar Usuario
			</a>
			<br/><br/>
			<div class="collapse" id="collapseExample">
			 <div class="well">
			  	<form method="post" id="formnewuser">
			  	<div class="row">
			  		<div class="col-lg-6">
						<div class="form-group">
						   <label for="exampleInputName2">Nombre Completo del Usuario</label>
						   <input type="text" class="form-control" id="nombre_real" name="nombre_real">
						</div>
			  		</div>
			  		<div class="col-lg-6">
						<div class="form-group">
					    	<label for="exampleInputName2">Username</label>
					    	<input type="text" class="form-control" id="username" name="username">
						</div>
			  		</div>
			  	</div>
			   	<div class="row">
			  		<div class="col-lg-6">
						<div class="form-group">
				    		<label for="password">Contrase&ntilde;a</label>
				    		<input type="password" class="form-control" id="password" name="password" >
				  		</div>
			  		</div>
			  		<div class="col-lg-6">
					 <div class="form-group">
					   <label for="passwordConfirm">Confirmar Contrase&ntilde;a</label>
					   <input type="password" class="form-control" id="passwordConfirm" name="passwordConfirm" >
					 </div>
			  		</div>
			  	</div>
			   	<div class="row">
			  		<div class="col-lg-6">
					  	<div class="form-group">
					    	<label for="rol">Rol del Usuario</label>
					    	<select class="form-control" id="rol" name="rol">
					    		<option value="1">Administrador</option>
					    		<option value="2">Recepcionista</option>
					    		<option value="3">Ejecutivo</option>		    
					    	</select>
					  	</div>
			  		</div>
			  		<div class="col-lg-6">
			  			<br />
						<center><button type="submit" class="btn btn-outline btn-primary btn-lg btn-block" onclick="submitFormNewUser()">Guardar</button></center>
			  		</div>
			  	</div>			  	
			   <input name="accion" value="agregar" type="hidden">				  
				</form>
			 </div>
			</div>
		</div>
	</div>
	<div class="row" align="right">
		<?=$this->paginationControl ($this->paginator, 'Sliding');?>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<div class="alert alert-success alert-dismissable">
               <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
               <a class="alert-link">Se muestran<?php echo $this->countArray ?> usuario(s).</a>
           </div>
			<br/>
			<div class="panel panel-info">
	           <div class="panel-heading ">
	                Usuarios Registrados:
	           </div>
	           <!-- /.panel-heading -->
	           <div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable-usuarios">
						<thead>
							<tr>
								<th>ID</th>
								<th>Username</th>
								<th>Nombre Real</th>
								<th>Estatus</th>
								<th>Rol</th>
								<th>Editar</th>
							</tr>
						</thead>
						<tbody align="center">
							<?php foreach ($this->paginator as $registro) { ?>
							<tr
								<?php 
									if ( $registro['activo'] == 0 ){
										echo 'class="bg-warning"';
									}
								?>
								>
								<td><?php echo $registro['id_user'] ?></td>
								<td><?php echo $registro['username'] ?></td>
								<td><?php echo $registro['realname'] ?></td>
								<td>
								<?php 
									if ( $registro['activo'] == 1 ){
									echo 'Activo';
									} else {
									echo 'Inactivo';
									}
								?>
								</td>
								<td>
								<?php
									switch ($registro['id_rol']) {
										case 1:
										echo 'Administrador';
										break;
										case 2:
										echo 'Gerencial';
										break;
										case 3:
										echo 'Operador';
										break;
									}
								?>
								</td>
								<td>
									<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal"
									onclick="datosform_edita_usuario('<?php echo $registro['id_user'] ?>','<?php echo $registro['username'] ?>','<?php echo $registro['realname'] ?>','<?php echo $registro['activo'] ?>','<?php echo $registro['id_rol'] ?>')">
									<i class="fa fa-pencil-square-o"></i>
									</button>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

<h1 id="live-search">Busquedas en listas</h1>

<div class="bs-docs-example no-code">
  <select class="selectpicker" data-live-search="true" data-width="auto">
		<option>DOS PUERTAS Y LANCERS</option>
		<option>DOUBLETREE HOTELS</option>
		<option>DOVER DE MEXICO, S.A. DE C.V.</option>
		<option>DOW CORNING DE MEXICO,   S.A. DE C.V.</option>
		<option>DOW CORNING DE MEXICO,   S.A. DE C.V.   </option>
		<option>DOW JONES TELERATE FINANCIAL INFORMATION SERVICES, INC</option>
		<option>DOW QUIMICA MEXICANA, S.A. DE C.V.</option>
		<option>DOWEL SCHLUMBERGER DE MEXICO, S.A. DE C.V.</option>  
		<option>DR JOSE POLAK, S.A. DE C.V.</option>
		<option>DR. FRANCISCO SANTINI Y ASOCIADOS</option>
		<option>DRAGOCO, S.A.</option>
		<option>DRESDNER BANK MEXICO, S.A.</option>
		<option>OFICINAS CORPORATIVAS</option>
		<option>EDUARDO VEGA Y COMPAÑIA, SUCESORES, S.A. DE C.V.</option>
		<option>EDUCACION PSICOLOGIA Y SALUD,  A.C.</option>
		<option>EDUCAL, S.A. DE C.V.</option>
		<option>EF SERVICIOS EN EDUCACION INTERNACIONAL, S.A. DE C.V.</option>
		<option>EFECTIVALE, S.A. DE C.V.</option>
		<option>EFFIX, S.A. DE C.V.</option>
		<option>EFFORT DE MEXICO, S.A. DE C.V.</option>
		<option>EGON MEYER, S.A. DE C.V.</option>
		<option>EIF LUBRICANTES MEXICO, S.A. DE C.V.</option>
		<option>EJECUTIVOS Y ASESORES EN TURISMO</option>
		<option>EJES TRACTIVOS, S.A. DE C.V.</option>
		<option>EKONOM,  S.A. DE C.V.</option>
		<Option>EQUIPO INDUSTRIAL "RYMACH"</Option>
		<Option>EQUIPO PARA EMBOTELLADORAS Y CERVECERIAS, S.A. DE C.V.</option>
		<Option>EQUIPOS AUTOMOTRICES NACIONALES, S.A. DE C.V.</option>
		<Option>EQUIPOS BIOMEDICOS PROFESIONALES,  S.A. DE C.V.</option>
		<Option>EQUIPOS COMPUTACIONALES DE MEXICO, S.A. DE C.V.</option>
		<Option>EQUIPOS DE TELECOMUNICACIONES Y REDES,  S.A. DE C.V.</option>
		<Option>EQUIPOS E INSTRUMENTAL MEDICO QUIRURGICO, S.A. DE C.V.</option>
		<Option>EQUIPOS ELECTROMECANICOS, S.A. DE C.V.</option>
		<Option>EQUIPOS ELECTRO-MEDICOS REQUENA,  S.A. DE C.V.</option>
		<Option>EQUIPOS INDUSTRIALES DE LIMPIEZA,  S.A. DE C.V.</option>
		<Option>EQUIPOS INTERFERENCIALES DE MEXICO</option>
		<Option>ESCUELA DE PERIODISMO CARLOS SEPTIEN GARCIA</option>
		<Option>ESCUELA INTERNACIONAL DE TURISMO</option>
		<Option>ESCUELA LIBRE DE DERECHO</option>
		<Option>ESCUELA NACIONAL DE CIENCIAS BIOLOGICAS</option>
		<Option>ESCUELA NACIONAL DE MEDICINA Y HOMEOPATIA ( IPN )</option>
		<Option>ESCUELA PANAMERICANA DE HOTELERIA, A.C.</option>
		<Option>ESCUELA SUPERIOR DE COMERCIO Y ADMON.</option>
  </select>
</div>
<br/>
	


</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel"></h4>
     </div>
      
     <form method="post" id="formedituser">
      	<input type="hidden" name="edita_id_user" id="edita_id_user">
      	<input name="accion" value="editar" type="hidden">
	     <div class="modal-body">
	        
			 <div class="form-group">
			   <label for="exampleInputName2">Nombre Completo del Usuario</label>
			   <input type="text" class="form-control" id="edita_nombre_real" name="edita_nombre_real">
			 </div>
			 <div class="form-group">
			   <label for="password">Nueva Contrase&ntilde;a</label>
			   <input type="password" class="form-control" id="edita_password" name="edita_password" >
			 </div>
			 <div class="form-group">
			   <label for="passwordConfirm">Confirmar Nueva Contrase&ntilde;a</label>
			   <input type="password" class="form-control" id="edita_passwordConfirm" name="edita_passwordConfirm" >
			 </div>
			 <div class="form-group">
			   <label for="rol">Rol del Usuario</label>
			   <select class="form-control" id="edita_rol" name="edita_rol">
			    	<option value="1">Administrador</option>
			    	<option value="2">Gerencial</option>
			    	<option value="3">Operador</option>		    
			   </select>
			 </div>
			 <div class="form-group">
			   <label for="rol">Estatus</label>
			   <select class="form-control" id="edita_activo" name="edita_activo">
			    	<option value="1">Activo</option>
			    	<option value="0">Inactivo</option>
			   </select>
			 </div>
	     </div>
	     <div class="modal-footer">
	       <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	       <button type="button" class="btn btn-primary" onclick="submitForm()">Guardar</button>
	     </div>
     </form>
   </div>
 </div>
</div>




   <!-- DataTables JavaScript -->
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables/js/jquery.dataTables.min.js"></script>
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables-plugins/dataTables.bootstrap.min.js"></script>
   <script src="<?= $this->baseUrl() ?>/css_complete/datatables-responsive/dataTables.responsive.js"></script>

   <!-- Page-Level Demo Scripts - Tables - Use for reference -->
   <script>
    $(document).ready(function() {
        $('#dataTable-usuarios').DataTable({
            responsive: true,
            "language":{
    "sProcessing":     "Procesando...",
    "sLengthMenu":     "Mostrar _MENU_ registros",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
        "sFirst":    "Primero",
        "sLast":     "Último",
        "sNext":     "Siguiente",
        "sPrevious": "Anterior"
    },
    "oAria": {
        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
}

        });
    });
   </script>





